### ISSUE TITLE
Allow for selecting other providers

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#10]
As per: https://docs.vagrantup.com/v2/providers/configuration.html

We should figure out a way to catch Parallels, VMware, and Hyper-V users in addition to VirtualBox.

**Comment by jeremyfelt** [comment]
This seems to be a pretty straight forward task. We're about to have Parallels support merged into VVV with https://github.com/Varying-Vagrant-Vagrants/VVV/pull/479, just a few extra config lines to parallel (ha) the VirtualBox config. I think VMWare may even be easier than that.

**Comment by zamoose** [comment]
I'm wondering if this might not help with #96, particularly if we can get HyperV working.

**Comment by zamoose** [comment]
Related to #131.

**Comment by zamoose** [comment]
Closing, as #136, #137, and #138 address.
