### ISSUE TITLE
Running p3 profiler plugin broke server?

### ISSUE THREAD

**Issue by thiagodebastos** [wpengine/hgv#106]
Hi there, I am new to Vagrant. I followed your docs and watched the video and had everything working perfectly in no time. However, after testing the plugins, the page got stuck after running the p3 profiler. After that I couldn't load http://hhvm.hgv.dev/ anymore, but could load http://php.hgv.dev/. Now neither load but http://hgv.dev/ is working as expected.

How can I help by debugging this?

**Comment by zamoose** [comment]
Unfortunately, P3 doesn't work with HHVM:

https://wordpress.org/support/topic/no-visits-recorded-3?replies=11

We ought to pull it out as a supported plugin. 

As to php.hgv.dev misbehaving: I'm wondering if this isn't memcached related. Try flushing it by running `sudo service memcached restart` and see if things return to normal.

Also, I would take a look at the logs for php.hgv.dev (at admin.hgv.dev/logs) and see if there are any HTTP 500's).

**Comment by thiagodebastos** [comment]
Thanks for that, I will do that next time it happens. It was a new project so I just restarted from scratch. 
Thanks for the quick response!

**Comment by michaelbeil** [comment]
This seems to be the best place for questions @thiagodebastos outside of Twitter :).

@zamoose is a frequenter of both.

**Comment by thiagodebastos** [comment]
Thanks @michaelbeil I'll keep asking here then :)
