### ISSUE TITLE
Windows Provision: No data in sites folder

### ISSUE THREAD

**Issue by KLVTZ** [wpengine/hgv#108]
Problem
-----------
We have a developer on our team that uses a Windows 7 machine. After running through the playbook, there is no data in the sites folder. Is this a permission issue as related to #96?

**Comment by zamoose** [comment]
@KLVTZ:
Interesting. Did the developer happen to catch the output from Ansible on provisioning?

Can they run a `vagrant provision` and see if a) anything gets output or b) usable debug output gets put out?

Thanks!

**Comment by bamtron5** [comment]
@zamoose @KLVTZ 
i captured a log during 'vagrant up',
i assume that covers provisioning for the 1st rnd.

https://github.com/bamtron5/logfile
Thanks for helping out.

**Comment by zamoose** [comment]
There's the problem right there:

```
==> hgv: TASK: [varnish | Fill the varnish GPG Key] ************************************ 
==> hgv: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true, "rc": 2}
==> hgv: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv: 
==> hgv: FATAL: all hosts have already failed -- aborting
```

It never finished provisioning, so it never got to the part about creating the directories. Please try a subsequent provision and see if it completes successfully.

**Comment by zamoose** [comment]
Aha! I bet I know what's going on here.

That line in the `invalid armor header` message is the very first line of the key, but you'll notice yours has a `\n` contained in it. This is an extra newline character and I think it's breaking the key. I'm willing to bet that the Windows Git clone used Windows CRLF line endings for the files and thus broke this particular one.

This could well crop up for others, in this file or in some other select ones. @markkelnar, we probably ought to look to enforce line endings at the repo level via [.gitattributes](http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes).

**Comment by KLVTZ** [comment]
@zamoose @markkelnar @bamtron5 would the suggestion here be appropriate for a windows machine that uses the git bash terminal? 

https://help.github.com/articles/dealing-with-line-endings/#platform-windows

I doubt it as this is responsible for the git client. Perhaps a setting windows users can do?

**Comment by bamtron5** [comment]
#110 I added the line you suggested to .gitattributes in the root of the hgv project. 

    * text=auto

i was returned the same error about armor headers being invalid.
@zamoose @KLVTZ @markkelnar 

``` bash
==> hgv: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true, "rc": 2
}
==> hgv: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzc
KC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1
+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ************************************************************
********
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=50   changed=44   unreachable=0    fail
ed=1
```

**Comment by zamoose** [comment]
Hey @bamtron5:
The `.gitattribute` fix will unfortunately only apply to all new checkouts and won't retroactively do much, if anything, at all.

You could follow the [instructions](https://help.github.com/articles/dealing-with-line-endings/#platform-windows) that @KLVTZ listed above, or to fix this one issue, I would advocate that you:

1. `vagrant ssh`
2. `sudo apt-get install dos2unix`
3. `sudo dos2unix  /vagrant/provisioning/roles/varnish/files/varnish-cache.gpg.key`
4. Try `vagrant provision` again.

See if this works!

**Comment by khromov** [comment]
Still having this problem upon checking out via GitHub Desktop  on a Windows machine. Has the file encoding changed again or is it some sort of automatic conversion causing this problem? Running `dos2unix` resolves the issue.

**Comment by ericmann** [comment]
There is a high likelihood that GitHub Desktop is mucking with your line endings when running a clone. I would highly advise either using the Git command line to clone the project initially, or continue using `dos2unix` to resolve the issue post-cloning.

**Comment by ericmann** [comment]
Also of note, we've updated the `.gitattributes` file on the _develop_ branch to force LF line endings (instead of Windows' default CRLF) in the future. However, if you're cloning `master`, you'll still get the old `.gitattributes` file.

**Comment by khromov** [comment]
@ericmann The `.gitattributes` file is probably the issue, since GitHub Desktop conforms to it. Great to hear it's being fixed once it gets into master.
