### ISSUE TITLE
Vagrant Push

### ISSUE THREAD

**Issue by rcjohnson** [wpengine/hgv#112]
It'd be awesome if 'vagrant push' could move your site to staging/production WP Engine sites.

**Comment by KLVTZ** [comment]
+1 on this. 

Now if only wpengine allowed sub-modules. For those doing work arounds, there is a bash script for deploy I would recommend: https://github.com/mehtryx/wpengine-deploy

**Comment by zamoose** [comment]
@KLVTZ:
That script looks intriguing. We may get ahold of the author and see about potential collaboration opportunities.

**Comment by KLVTZ** [comment]
@zamoose it has helped us tremendously. The main logic behind it is its use of a temp folder that acts as a mediator between different repos. Having contributed a very tiny PR, I can say that the author is very open and willing to collaborate.

**Comment by michaelbeil** [comment]
+1

**Comment by zamoose** [comment]
@KLVTZ:
I'm not a WPE employee, but as I understand it, when you Git push your code to WPE, it goes to an intermediate repository, from whence it is deployed to your actual staging/production instances; that is, you're not pushing directly to the web root. I believe the lack of submodule support is due primarily to this fact.
