### ISSUE TITLE
Install the Mercury recommended S3 plugin.

### ISSUE THREAD

**Issue by rcjohnson** [wpengine/hgv#114]
Since WP Engine Mercury recommends a plugin to manage assets on S3, we should include that as a part of the vagrant installation so that it is a true verification layer for Mercury, and goes ahead and moves all assets up to S3 in anticipation of launch.

**Comment by michaelbeil** [comment]
Great idea!

**Comment by JPry** [comment]
What is the specific plugin that is recommended? With some of the recent changes this would be a one-line addition to the `provisioning/group_vars/all` YAML file.

**Comment by stephen-lin** [comment]
@JPry It's S3-Uploads. https://github.com/humanmade/S3-Uploads
