### ISSUE TITLE
Split provisioning like VVV

### ISSUE THREAD

**Issue by michaelbeil** [wpengine/hgv#119]
Would separating sites for provisioning be something to consider for HgV?

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/611 

Or perhaps it's a little beyond the vision of HgV?

**Comment by zamoose** [comment]
Define "split"/"separating".

**Comment by michaelbeil** [comment]
Meaning a user could provision either php.hgv.dev or hhvm.php.dev and not both.

**Comment by zamoose** [comment]
#160 may do this, @michaelbeil...?

**Comment by michaelbeil** [comment]
I think so.
