### ISSUE TITLE
Update WP-CLI to latest version

### ISSUE THREAD

**Issue by rachelbaker** [wpengine/hgv#121]
WP-CLI currently loads version 0.17.1, [bump to version 0.18.0](https://github.com/wpengine/hgv/blob/master/provisioning/group_vars/all#L10).

**Comment by zamoose** [comment]
I've got a PR in-flight on this one. Thanks @rachelbaker!

**Comment by rachelbaker** [comment]
@zamoose Sorry, I didn't catch your message in time.  I submitted #122, but feel free to use your PR.

**Comment by zamoose** [comment]
Committed, thanks!
