### ISSUE TITLE
Create wp-config: intermittent template error

### ISSUE THREAD

**Issue by kevcenteno** [wpengine/hgv#124]
Host: Mac OS X Mavericks

`wordpress | Create wp-config for {{ enviro }}` fails intermittently.  The string it fails at changes each time it fails.

A second provisioning run helps 99% of the time.

```
==> hgv: TASK: [wordpress | Create wp-config for php] **********************************
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
```

**Comment by zamoose** [comment]
@kevcenteno:
I've noticed this myself. It's due to the salts coming from wp.org having improperly-escaped values.

I need to re-do that part of the WP provisioning process anyways and have been looking at solutions but no clearly obvious one has presented itself yet.

**Comment by kevcenteno** [comment]
Ah, I actually might be able to help!  Thank you for the direction :+1:

**Comment by zamoose** [comment]
Re-opening. I've figured out *why* this is happening. Now it's time to figure out *how to make it stop*.

Essentially, the random salt generator at wp.org will occasionally return strings containing "{%" or "{{". Ansible passes templates to Jinja2, which interprets those character sequences as 

* control structure invocations
* template tags

respectively. 

There's *got* to be a way to keep Ansible/Jinja from attempting double-interpolation. Now to figure out what that is.

**Comment by kevcenteno** [comment]
Yeah,  this is absolutely the issue. Unfortunately, ansible doesn't allow you to handle templating errors, either. 

Maybe we can revisit the bash script solution?

**Comment by zamoose** [comment]
Attempting a fix with a {% raw %}...{% endraw %} block. Let's see if it
works.

On Thu, Apr 30, 2015 at 12:58 PM, Kevin Centeno <notifications@github.com>
wrote:

> Yeah, this is absolutely the issue. Unfortunately, ansible doesn't allow
> you to handle templating errors, either.
>
> Maybe we can revisit the bash script solution?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/124#issuecomment-97879659>.
>



-- 
-Doug

**Comment by kevcenteno** [comment]
Fingers crossed. I think I tried that but it would still fail.

**Comment by zamoose** [comment]
@kevcenteno {% raw %} was a bust, but `replace()` seems to work for me.

**Comment by shaneog** [comment]
I've noticed that it also breaks on this character: `>`
