### ISSUE TITLE
Is it possible to run this with the following versions?

### ISSUE THREAD

**Issue by jnthnclrk** [wpengine/hgv#140]
```
$ git --version
git version 1.8.4
$ vagrant -v
Vagrant 1.7.2
$ vBoxManage -v
4.3.26r98988
```

**Comment by zamoose** [comment]
Definitely.

**Comment by jnthnclrk** [comment]
OK, just wanted to double check as I'm running into problems and http://wpengine.com/mercury/how-to-start/ was very specific.

**Comment by zamoose** [comment]
What sorts of problems?

**Comment by jnthnclrk** [comment]
OK, if that's not maybe this: https://github.com/wpengine/hgv/issues/141

**Comment by zamoose** [comment]
Closing out in favor of #141.
