### ISSUE TITLE
Uploads by Proxy?

### ISSUE THREAD

**Issue by jnthnclrk** [wpengine/hgv#143]
Uploads by Proxy ( https://wordpress.org/plugins/uploads-by-proxy/ ) is a great plugin for dynamically pulling assets from production uploads/... It doesn't seem to work out-of-the-box with hgv. Wondering if anyone has figured out how to make it work?

**Comment by zamoose** [comment]
Did you perform the steps in the README? 

```
Setup
In most cases, you should be able to activate the plugin and go. If the plugin does not work automatically, then you need to set the address of your live WordPress install in wp-config.php, like this:

 define('UBP_SITEURL', 'http://example-live.com/wordpress');
If you are on a staging server (not a local development environment) you may need to force the plugin to run with define( 'UBP_IS_LOCAL', true ); in wp-config.php. Do not set this on a live site!
```

**Comment by jnthnclrk** [comment]
Yep, tried all of that. UBP_IS_LOCAL caused some errors actually.

**Comment by stephen-lin** [comment]
@jnthnclrk This plugin will ultimately conflict with a required plugin for Mercury, S3-Uploads, which should be included and used in dev locally. The first import, while S3-Uploads is deactivated, will go fine, but any updates from Uploads by Proxy once S3-Uploads is active will not work.
