### ISSUE TITLE
Unable to pass commands to `vagrant ssh`

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#147]
As pointed out in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/610, our chosen solution to the "not a tty" bug actually breaks `vagrant ssh -c [command to run on VM]`. No output will ever be returned in our method.

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/633 may be the only real way forward (similar to how we used to work around this), though you will likely still see the "not a tty" error on the first `vagrant up`.

**Comment by kim07** [comment]
:

**Comment by jeremyfelt** [comment]
I'm testing this out for VVV now and it seems to hide the message on an initial `vagrant up` (after `vagrant destroy`) as well as `vagrant provision`.
