### ISSUE TITLE
Use dynamic inventory to allow custom host names

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#15]
I'm liking the notion of making hhvm.\*, php.\*, cache.hhvm.\*, cache.php.\*, etc. all work on single instances of WordPress, as per @markkelnar's ideas in HipChat. I think it would be extra-compelling if we could allow for dynamic inventory creation and allow folks to add their own lists of host names/sites to a single file (likely a YAML one) stored somewhere outside of the provisioning tree. Then we can just run the `-i` on Ansible and point it to a shell, PHP, whatever script that populates the JSON catalog with our defaults *and* reads the YAML file to pull in the custom requests. 

We could also do this for per-site plugin and theme loadouts.

Downside: Regular people would have to learn YAML.
Upside: Much more flexibility.

We would also need to dynamically populate the host list in the `Vagrantfile` using some Ruby in order to make sure the new domains get picked up by the `vagrant-hostsupdater` plugin.

This solution should ideally solve

* [ ] #7 
* [ ] #16

**Comment by zamoose** [comment]
Here's what I'm thinking, roughly:

We create a dynamic inventory script, using PHP, bash, or whatever makes the most sense. This script returns the properly-formatted JSON that Ansible expects from a dynamic inventory. We inject the default domains, etc., through the script but then allow users to specify their custom domains and what have you in a file, and since we're using Ansible, it probably makes sense to have it be a YAML file. Again, for example, we could look for a file at `hgv_data/customdomains.yaml`.

We would then create a specification for the file (what our parser would look for) and then we could return domains, custom group_vars, etc. Additionally, with a little bit of Ruby injected into our [Vagrantfile](/wpengine/hgv/Vagrantfile), we could parse that YAML file and inject any domains we find into the actual provisioning process so that `vagrant-hostsupdater` could pick up and allocate the user-supplied domains automatically on `vagrant up`.

Does that make sense?

**Comment by markkelnar** [comment]
@zamoose I've got some ideas on this and started playing around with adjusting the tasks under the wordpress role.  I don't have anything concrete yet worth sharing, but hope to soon.

The difficult part is coming up with a format for the YAML file that makes sense.  Do you have a direction on what you think that might look like yet?  I'll post a sample of mine as it comes together too.

**Comment by zamoose** [comment]
@markkelnar I've been toying around with a YAML file format. I'm thinking we should make HGV work off of two YAML files -- one a reserved one that ships with HGV and a second, optional one provided by the end users. The inventory script would then combine the two and spit out a valid inventory.

Here's the format I've been using:

https://gist.github.com/zamoose/6c247080078c96e682dc

I'll link the inventory script in as well. There's also a few changes to the `Vagrantfile` that allow it to grab the domains and feed them into `vagrant-hostsupdater` for automagic domain name provisioning.

**Comment by markkelnar** [comment]
I believe this primary functionality is provided with #154 and once we document how to use it, it'll be complete.  Let's close this issue because the functionality exists and work on the documentation part under another issue.
