### ISSUE TITLE
Unable to display fatal errors

### ISSUE THREAD

**Issue by nabhacosley** [wpengine/hgv#150]
I was able, by editing /etc/php5/fpm/php.ini, to get error logging working, but fatal errors won't display in the browser even though `var_dump( ini_get_all() );` reports that `display_errors` and `display_startup_errors` are both on.

It seems like error reporting was intended to be on by default on a clean setup, which this was. Is something wrong on my end?

Here's the code I have in the index.php of an otherwise blank WordPress theme:

```

<pre><?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(E_ALL);

set_error_handler("var_dump");

echo $test; // generates warning, no variable defined — this is visible unless there's a fatal error

echo 'test';

sdfsd // generates fatal error, but that causes a white screen of death

var_dump( ini_get_all() );

phpinfo();

?></pre>

test
```

**Comment by nabhacosley** [comment]
Well, I've been able to get fatal errors to show in some files, now, but not others. For example, fatal errors in the WordPress loading sequence through `wp-blog-header.php` are reported — but when that file loads `/wp-includes/template-loader.php`, the errors are no longer displayed. Interesting, right? I can't figure it out.

**Comment by nabhacosley** [comment]
WP_DEBUG_DISPLAY was set to false in local-config.php. My bad!

**Comment by zamoose** [comment]
Yup, this is the  intended behavior. Errors will be logged to the web server logs, available at admin.hgv.dev/logs or if you enable the Query Monitor plugin inside of WP.
