### ISSUE TITLE
Existing WP with wp-config.php failing vagrant up

### ISSUE THREAD

**Issue by markkelnar** [wpengine/hgv#156]
When copy files for an existing WP install into hgv_data/sites/hhvm/ that contains wp-config.php, the wordpress.yml task that uses wp-cli to check 'core is-installed'.  Encounters an error connecting to mysql db using the existing db creds in the wp-config.php that was not provided by HGV, therefore does not contain the condition to use the HGV provided local-config.php file.

```
==> hgv: TASK: [wordpress | Check whether the WP install has been run previously] ******
...
==> hgv: <h1>Error establishing a database connection</h1>
==> hgv: <p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code>127.0.0.1</code>. This could mean your host's database server is down.</p>
==> hgv: <ul>
==> hgv: 	<li>Are you sure you have the correct username and password?</li>
==> hgv: 	<li>Are you sure that you have typed the correct hostname?</li>
==> hgv: 	<li>Are you sure that the database server is running?</li>
==> hgv: </ul>
==> hgv: <p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>

**Comment by zamoose** [comment]
Hmmm. The only right way to handle this is probably documenting this condition for an import scenario, unless I'm missing something here.

**Comment by zamoose** [comment]
@markkelnar:
I've been giving this some thought -- what is your expected outcome here? Should HGV debug this *for* people, or should it just print a warning and continue provisioning, or...? I've been toying around with having some sort of "WordPress linter", but I think that's probably *way* too much effort for what ought to be a step-by-step documentation "fix". "If you want to use an existing WP install, you'll need to...", etc.

**Comment by markkelnar** [comment]
Well, if I'm moving over an existing WP from another directory and vagrant up for the first time, I think it should not break provisioning.  Ansible should do it's thing, the WP should be usable, the database tables created and my local domains I configured should work.  That would be ideal.  

Maybe instructions are to 'move your existing non-HGV wp-config.php out of the way'.  And be done with it.

Or, should the wp-config.php, if not one created by HGV, be overwritten and replaced by the HGV provisioned one?  We could put some 'markers' in the HGV provisioned wp-config.php and look for those existing instead of just looking for the file existing.  And if those markers don't exist, drop in the wp-config.php file that will make HGV happy.

Or, inline edit the customer provided wp-config.php file to add in what HGV needs to operate, ie. include local-config.php.  But this one could get hairy pretty quickly.
