### ISSUE TITLE
Is it possible to have one WP on disk and database used by HHVM and PHP-FPM domains?

### ISSUE THREAD

**Issue by markkelnar** [wpengine/hgv#16]
Why does each WP in the vagrant (HHVM and PHP-FPM) have their own WP in their own docroot?  Why not have each use the same one WP on disk?

With each having their own copy of WP and database, it's double the work to make a code change to a plugin, theme or code and test it with HHVM or FPM.  Files and database has to be changed in two location.

And there's not really anything different between the local-config.php and wp-config.php, looks like.
Other than that cache domain logic for the WP_HOME/SITEURL defines.

Can we consider one docroot for the WP and HHVM and FPM server from there?  Is it possible?  Are there side effects or issues around it?

@zamoose brought up the point about serialized database options containing a domain might be effected by this.  I'd like to get my hands on that use case and investigate it's options.

**Comment by zamoose** [comment]
#7 is also a part of this whole process. Collapsing all WP installs for both PHP and HHVM into single installs simplifies this entire thing greatly. Then we'll just catch the HTTP_HOST portion of the request and munge it so WP understands it, allowing people to bring their own example.io addresses and have php.example.io, hhvm.example.io and cache.* work automagically.

**Comment by asmartbear** [comment]
Love it!  This would be huge for any developer.

**Comment by michaelbeil** [comment]
:+1:

**Comment by markkelnar** [comment]
Made a few changes to ansible to make this change feasible.  I also added a new domain that will share the WP in the hhvm docroot.  We intend to deprecate the php docroot, document it acccordingly and eventually stop creating that.  

Do we consider this issue complete for release 1.1?

**Comment by zamoose** [comment]
I've been heads-down on another project and haven't gotten a real good chance to get caught up here. Mind if I spend some time with the changes you've made thus far?

**Comment by markkelnar** [comment]
With the addition of fpm.hgv.dev, this is now proven possible.  We will have to decide a course of action for php.hgv.dev; deprecation, completely removing it from usage, or point it at the other WP.  We will also have to update documentation.

Closing this issue.
