### ISSUE TITLE
Bedrock setup with wpengine

### ISSUE THREAD

**Issue by KLVTZ** [wpengine/hgv#163]
Issue
--------
Improve workflow in using Bedrock with Mercury.

Discussion
---------------
[Bedrock][bedrock] the very popular Wordpress stack takes advantage of modern development practices when designing a custom Wordpress folder structure. This isn't the first occurrence of such a layout. Many modern projects isolate Wordpress core into its own application folder. Because of this, I wonder if we could extend the usability and workflow in using the two together?

Two areas we would want to improve upon is:

- nginx server root path to wordpress installation
- wordpress home and site-url constant definitions

Implementation
---------------------
In the following example, I have configured wpengine environment and bedrock setup to work together. By this example, I want to bring attention to some steps we can automate or improve setup of a custom wordpress project. 

Currently, nginx configuration for both `hhvm-hhvm.conf` and `hhvm-php.conf` assumes that Wordpress will live in the following folder structure: `/nas/wp/www/sites/hhvm/`. However, bedrock uses composer to manage Wordpress to its own install directory: `web/wp`. According to [bedrock's installation guide][installation] we want to set our site vhost document root to `/path/to/site/web/`. Inside the web folder, there is an index file that takes care of the rest.  Therefore, I need to set the root property in the server block to: `/nas/wp/www/sites/hhvm/web/`. Is it possible we can make this configurable before provisioning?

The other issue is how bedrock uses environment variables. By using [phpdotenv][phpdotenv], bedrock defines both `WP_HOME` and `WP_SITEURL` constant. We need to remove that from the bedrock's [config/application.php][application] file. Next, we have to add the some statements from mercury's [local-config.php][local] file. More specifically:

```php
global $memecached_servers;

$memcached_servers = array(
	'default' => array(
		'127.0.0.1:11211'
	)
);

$wp_cache_key_salt = 'wpe_hhvm_1_';

if( isset($_SERVER['HTTP_HOST']) ) {
	define('WP_HOME', 'http://'.$_SERVER['HTTP_HOST']);
	define('WP_SITEURL', 'http://'.$_SERVER['HTTP_HOST'].'/wp');
	$wp_cache_key_salt = 'wpe_hhvm_'.$_SERVER['HTTP_HOST'].'_';
}

/** Object Cache Key Salt per domain */
define('WP_CACHE_KEY_SALT', $wp_cache_key_salt);
```

This most certainly isn't mercury's issue, because at this point, this statement is defined from within a custom configurable file within bedrock: [config/environments/development.php][development]. We would do the same for a staging environment or production. Nevertheless, I wanted to highlight this as something that could be automated. 

Granted, both these issues can easily be automated by a script. But I'm curious if there are any more ideas on improving this startup.

Notes
--------
- In this issue, we will assume a team will want to manage their own Wordpress core in relation to wpengine.
- Bedrock has an ansible playbook, but we will assume that a team will want to use mercury environment in relation to wpengine.

[bedrock]: https://stash.automotive.com:7443/projects/Q4WP/repos/ares-starter/
[installation]: https://github.com/roots/bedrock#installation
[application]: https://github.com/roots/bedrock/blob/master/config/application.php
[phpdotenv]: https://github.com/vlucas/phpdotenv
[local]: https://gist.github.com/52e9e97ebee91363d7ee
[development]: https://github.com/roots/bedrock/blob/master/config/environments/development.php

**Comment by zamoose** [comment]
@KLVTZ:
If I'm reading this correctly, this would largely be solved by allowing sites to specify a custom docroot other than the default in `/nas/wp/www/sites/[sitename]`, correct?

**Comment by KLVTZ** [comment]
@zamoose Yes! By allowing the user to define a custom path, other than the default, would benefit projects that want to isolate wordpress core into a different folder.

Apologies for the verbose issue, I wanted to outlay a situation that I others may face.

**Comment by stephen-lin** [comment]
@KLVTZ If you wanted to, feel free to submit a PR for this. We can definitely review and merge if things look good. Outside of that, this is fairly low priority for us at the moment and may or may not be something we revisit in the future.

**Comment by KLVTZ** [comment]
@stephen-lin for such a PR, what files would I be most concerned with? Would this be an issue involving Vagrant or that of ansible and it's provisioning setup?

**Comment by ericmann** [comment]
@KLVTZ Some of the issues here are merely that Bedrock doesn't necessarily fit the goals of the Hgv project, so making things Bedrock-compatible is fairly low priority on our radar. _That being said,_ it's also not necessarily a blocker.

In other words, we'd need to see from your perspective what would need to change within Hgv to support Bedrock-style WordPress development.

## Hgv

The overall goal of Hgv is to serve as a Mercury emulator in a local Vagrant box. Ideally, developers can test their themes/plugins/sites in a Mercury-style environment locally, then deploy any potential changes to the server running things in production. 

(See #112 for some of our initial conversations around supporting `vagrant push` for easy deployments. See http://wpengine.com/git/ for some documentation around how `git push` already enables efficient project deployment on WPEngine.)

To that end, any specific project configuration changes should impact _just_ how the project works and not change the way Ansible builds the Vagrant VM itself.

## How I perceive Bedrock

Having never personally used Bedrock, most of this is knowledge gleaned from the GitHub repository and various blog posts I've found. From the looks of things, Bedrock exists to clean up the way the end server is configured by placing WordPress and some other files in non-standard directories and pulls in some other tools for better project management.

I'm not at all opposed to this, but certain elements of how Bedrock works are inherently incompatible with the current deployment tools/workflows supported by (or in development for) Hgv/Mercury. Specifically:

- Composer is not currently supported in production - so pulling in additional dependencies is a no-go
- WPEngine does not expose or support custom environment variables at this time

These two components are major blockers to being able to support Bedrock. That, and I'm just not sure what a Bedrock-powered site would even look like within Hgv. If you have a clear plan in mind, though, feel free to document things here to demonstrate and/or submit a PR showing what (if anything) needs to change to support Bedrock's development workflow.

**Comment by zamoose** [comment]
I think that one thing that would help Hgv work well for these sorts of things (or Laravel, etc.) is to have a docroot exist one directory below what we're calling "enviro" right now. Because of the way that other projects organize files (with config/, public/, lib/, etc. directories), being able to spin up a new environment in such a fashion would be very useful. 

That change alone wouldn't be very disruptive, IMHO. 

--
Doug Stewart

**Comment by KLVTZ** [comment]
@ericmann thanks for the input. After having discussed using bedrock with wpengine. They will not budge. I agree that the environment variables they currently define can be quite difficult to leverage. However, composer is possible on wpengine as a standalone binary. Using it to manage your vendor folder on every deploy is not due to lack of hooks. Therefore wpengine's repo can grow quite large in deltas. One of the reasons why having a build server is important before pushing directly to wpengine.

If wpengine could leverage hooks, I would be in paradise. I have yet to hear from them as to why this has not been implemented. Hopefully soon. 

@zamoose I agree, having control over docroot alone would make this a more flexible environment.

HGV is at the mercy of what is possible on wpengine. Until wpengine leverages more control to developers, such desired features may not be adapted. Why? Because this project's purpose is to give developers an environment to work in that replicates what is possible in production. Realizing this, it only seems more viable to persuade them to consider such options above.

**Comment by ericmann** [comment]
I'm going to close this for now until WPE has finished some work on hooks. We can revisit/reopen at that time.
