### ISSUE TITLE
Plugins entry in the config file?

### ISSUE THREAD

**Issue by marcobarbosa** [wpengine/hgv#188]
Hi,

I hope this hasn't been asked before as I couldn't find any information on this :)

I was looking into specifying Wordpress plugins in the config yml file so you get them for "free" when running vagrant. Just like you did with `query-monitor`, `debug-objects` and `debug-bar`.

I've noticed this is documented in the [VCCW](http://vccw.cc/#h2-4) by adding a plugins entry like so:

```
wp:
  (...)
  plugins:
    - contact-form-7
    - jetpack
```

Is there any way to do such a thing with HGV?

**Comment by zamoose** [comment]
@marcobarbosa I had some of this working in a prototype for the custom domains solution. It oughtn't be too hard to implement.

**Comment by marcobarbosa** [comment]
@zamoose Care to show an example?

**Comment by zamoose** [comment]
@marcobarbosa see #190.

**Comment by marcobarbosa** [comment]
Thanks! I'll keep an eye on that one :)

Much appreciated :+1:
