### ISSUE TITLE
Provisioning Error after varnish | Fill the varnish GPG key - provisioning failed

### ISSUE THREAD

**Issue by don-dev** [wpengine/hgv#193]
I am on windows 8.1 trying to inflate this env. when provisioning reaches a fatal error and stops.

*****************
==> marriott-hgv: ok: [127.0.0.1]
==> marriott-hgv:
==> marriott-hgv: TASK: [varnish | Fill the varnish GPG Key] *******************
*****************
==> marriott-hgv: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true
, "rc": 2}
==> marriott-hgv: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbH
P1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> marriott-hgv:
==> marriott-hgv: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1z
xMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> marriott-hgv:
==> marriott-hgv: FATAL: all hosts have already failed -- aborting
==> marriott-hgv:
==> marriott-hgv: PLAY RECAP ***************************************************
*****************
==> marriott-hgv:            to retry, use: --limit @/root/playbook.retry
==> marriott-hgv: 127.0.0.1                  : ok=55   changed=4    unreachable=
0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I set this up on a linux install and it worked beautifully- I have other boxes on windows working correctly- so I am trying to find the error with this provisioning process.

can some body help?

**Comment by ericmann** [comment]
@don-dev This is an issue with how Windows handles line endings when it clones projects. Mac and Linux use `\n` to define the end of a line. Windows uses `\r\n`. When you clone the project on Windows, if your machine is cloning with Windows-style line endings, then it will add the `\r\n` everywhere.

Unfortunately, this will bleed through into the Linux VM and corrupt some of the files we need for provisioning - as seen in your error messages above referencing a string that ends in `\n`.

We've attempted to prevent this from happening with the `.gitattributes` file in the root of the project, but some Windows installations can be a bit more stubborn about it. I'll see if there's something we can do to make `.gitattributes` more reliable going forward.

***However***, that still won't fix your existing checkout. So let's take care of that.

What we need to do is force the GPG key to have the correct line endings so provisioning will work as expected. We can do that with a cool Linux tool called `dos2unix`:

1. Make sure your VM is running (even though provisioning isn't complete).
1. `vagrant ssh`
1. `sudo apt-get install dos2unix`
1. `sudo dos2unix /vagrant/provisioning/roles/varnish/files/varnish-cache.gpg.key`
1. Exit out of the VM's ssh session
1. `vagrant provision` from the Windows host.

What all of this does is install the tool, run it against the file that was erring to set up the correct line endings, and then re-provision with the fixed files.

Once you take care of the above, please let me know if you run into any other problems getting things started.

**Comment by don-dev** [comment]
thank you this worked// I noticed your box uses other methods to detect windows, this should run as part of the provisioning process.

note* i had to use this command on other files

**Comment by don-dev** [comment]
Wanted to comment for others running into this- I had to 

`sudo dos2unix /vagrant/provisioning/roles/admin/files/mailhog_ini`

**Comment by nicoladj77** [comment]
I have a different problem on windows: running vagrant up stops at certain point. I t seems to get stuck,  
after calling Powershell

![image](https://cloud.githubusercontent.com/assets/333069/8785302/06a11e34-2f27-11e5-887f-82870454548c.png)

**Comment by nicoladj77** [comment]
My problem was with Powershell version that needs to be 3 or higher. Since this is the first time i have this problem ( had used VVV and VIP-Quickstart without issues ) I think it's better to document this.

**Comment by linuxbastard** [comment]
@don-dev the command should be:

`sudo dos2unix /vagrant/provisioning/roles/admin/files/mailhog_init`

You were missing the "t" at the end and "mailhog.ini" doesn't exist. I'm assuming you did this because of the mailhog provisioning error as well?
