### ISSUE TITLE
Web-based admin tools

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#2]
We should install some useful web-based admin tools for the various components we include, such as:

- [ ] Webgrind
- [x] phpMyAdmin
- [x] [phpMemcachedAdmin](https://code.google.com/p/phpmemcacheadmin/)
- [ ] [Mailcatcher](http://mailcatcher.me/)
- [x] [PML](http://pimpmylog.com/)

**Comment by zamoose** [comment]
I've been having the same issues with getting Mailcatcher running as the VVV team:

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/464

Looks like they may have a solution but it needs some testing.

**Comment by markkelnar** [comment]
I created two separate issues, one for each of webgrind and mailcatcher.  Those can be targeted at a later milestone.  Closing this one as is.
