### ISSUE TITLE
Best way to edit Varnish config?

### ISSUE THREAD

**Issue by khromov** [wpengine/hgv#209]
I'm spinning up a HGV environment and would like to do some work on the Varnish config. Is there an easy way to move it to the /config folder so that it can be easily editable outside the VM?

**Comment by khromov** [comment]
I would also like to distribute this "down the line" for other people to pull down and spin up easily. Optimally, I'd just make a repo containing my yml file and a bash script that pulls down HGV and moves files to the appropriate locations, then spins up a HGV instance. If there is any easier way of doing this, I'd love to hear it!

**Comment by ericmann** [comment]
What kind of customizations do you want to do to the Varnish config? It's not currently editable outside the VM as the goal is to empower editing code and testing against a WPE-consistent environment; your changes might be such that they'd make HGV no longer reflect WPE production.

**Comment by khromov** [comment]
@ericmann I was honestly just looking for a nice development environment, the readme said this was more of a general environment "to allow people in the WordPress community to run a single Vagrant for developing, debugging, and deploying".

I don't wish to keep my project compatible with WPEngine, just thought this looked like a nice project, but I guess a fork is the best option then if there is no interest in making the config files easily editable.

**Comment by ericmann** [comment]
@khromov I'm not writing off your change entirely - there's likely a chance we could still incorporate your necessary changes without breaking compatibility with WPE's environment. But to know whether or not that's doable, I'd need to better understand what changes to the config you need to make.

**Comment by khromov** [comment]
@ericmann At the core, it would be nice to use hgv as a base and being able to augment it by adding other software and configs at all level of the stack, be it adding a package or modifying some config file. 

The reason for not just forking is that it's still beneficial to receive downstream patches for the Ansible Playbooks.

Maybe there's some way to do this that I'm not seeing? 

I did play around with adding hgv as a submodule but it doesn't provide the full flexibility I described, and it also doesn't provision cleanly. (Seems to be an issue with static paths. [Relevant SO](http://stackoverflow.com/questions/10144149/git-status-returns-fatal-not-a-git-repository-but-git-exists-and-head-has-prop))

**Comment by markkelnar** [comment]
@khromov, here's one approach that might satisfy what you're looking to do. 

Make use of ansible variables like this ... ansible allows for the src= parameter in the template task to accept a variable.  Use a variable in the template task in https://github.com/wpengine/hgv/blob/master/provisioning/roles/varnish/tasks/main.yml#L18 .

Add a new file provisioning/roles/varnish/defaults/main.yml with a variable named 'varnish_default_vcl_path' with the current template file path 'etc/varnish/default.vcl'.  

This then allows for the path in this variable to be overwritten by another yml file, during provisioning.  Then bin/hgv-init.sh could check for that file and pass it to the playbook when it is found to exist (see http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line).  That file might live in hgv_data/config/ansible.yml.  Then you add variables to your ansible.yml config file to tweak the HGV environment.

I'll concur with @ericmann's concern about diverging from the WPE development environment, but I'll also express excitement in allowing end user's like yourself to be able to use the benefits of what HGV provides to your advantage.

Relatively few lines of code to change to make this happen.  Any thoughts?

**Comment by markkelnar** [comment]
Ok, I couldn't help and wrote some code to try and solve this.  Check out that PR and let me know if that does what you're thinking.
