### ISSUE TITLE
Vagrant HostUpdater Plugin Install Issues

### ISSUE THREAD

**Issue by allenmoore** [wpengine/hgv#215]
I had issues installing vagrant-hostupdater on two different machines (MacBook Pro Retina with OS X Yosemite and a desktop running Ubuntu 15.04).

After searching for a solution, I followed the directions on this issue on the vagrant-hostupdater github page -- https://github.com/cogitatio/vagrant-hostsupdater/issues/45#issuecomment-44220738.

Here are the steps:
```
sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install nokogiri -v '1.6.2.1'

sudo vagrant plugin update vagrant-vmware-fusion
```

Before installing vagrant-hostupdater, I installed the vagrant-hostupdater ruby gem:

```
gem install vagrant-hostsupdater
```

I was then able to install vagrant-hostupdater:

```
sudo vagrant plugin install vagrant-hostsupdater
```

This is related to https://github.com/wpengine/hgv/issues/120.

**Comment by ericmann** [comment]
Fixed by #222.
