### ISSUE TITLE
Upload Limits

### ISSUE THREAD

**Issue by andrew40** [wpengine/hgv#224]
Anyone know where i can increase the upload limits to import an XML file to setup a dev site for WPEngine?

I'm assuming the file isn't local and thus within vagrant, so will need to ssh in to change?

As an enhancement would it be possible to keep the files in a config directory for ease of access such as php.ini and nginx.conf?

**Comment by markkelnar** [comment]
Hello @andrew40.  We have this exact mechanism available to overwrite default values used during ansible provisioning.  It's available right now in the develop branch targeted for the 1.4 release.

Here's how that's done: https://github.com/wpengine/hgv/blob/develop/provisioning/roles/nginx/templates/nas/wp/www/sites/dashboard/GETTINGSTARTED.md#maintain-your-own-overrides-file

Work was done here https://github.com/wpengine/hgv/pull/211

It's a couple of Nginx and HHVM config files that are using small default right now for the `master` branch.

Hope this was helpful.

**Comment by ericmann** [comment]
As 1.4 has been released and this mechanism is available, I'm closing this issue for now. If it comes up again (or if you find a further issue with the mechanism) we can re-open.
