### ISSUE TITLE
Are there docs to configure Multisite?

### ISSUE THREAD

**Issue by aaronware** [wpengine/hgv#229]
I went through the online documentation, hgv.dev docs the limited items in the wiki but I didn't see a straight forward way to provision a multisite install.

I setup a custom multisite.yml and I have setup a few entries within the config.
I then updated wp-config.php to convert the install to a multisite.
lastly as usual if you are on apache you can setup an updated .htaccess to do it's business.

But how do I set up the redirects for nginx?

**Comment by markkelnar** [comment]
Hello @aaronware.  We've actually been working on multisite support.  It's currently available in the develop branch and targeted for the 1.4 release.  https://github.com/wpengine/hgv/pull/221

To set that up, in your hgv_data/config/sites/foo.yml file, add 'multisite: directory' or 'multisite: domain' to the `wp` hash.

Run vagrant provision and at that point, the Nginx rewrite rules will be added for that WP.

If you were created a new WP (it didn't exist yet), it will be provisioned, with the correct values in wp-config.php.

**Comment by aaronware** [comment]
Thanks @markkelnar. I'll give it a try.
