### ISSUE TITLE
Vagrant hangs after Vagrant Up on hgv: Clearing any previously set forwarded ports

### ISSUE THREAD

**Issue by rpasillas** [wpengine/hgv#231]
Windows 7 64bit.

After I run the first Vagrant Up, the process holds at `==> hgv: Clearing any previously set forwarded ports...` for at least an hour. Stopping the process with CTRL + C, returns  a cleanup message `==> hgv: Waiting for Cleanup before exiting...` that also seems to hold indefinitely.

**Comment by ericmann** [comment]
What versions of VirtualBox and Vagrant are you running? The port clearing mechanism is native to Vagrant itself (not HGV) so there might be an issue deeper in the stack.

**Comment by stephen-lin** [comment]
Closing because of no response.
