### ISSUE TITLE
Getting mailhog error when provisioning

### ISSUE THREAD

**Issue by linuxbastard** [wpengine/hgv#239]
TASK: [admin | Ensure mailhog is enabled and will start on boot.] *************
failed: [127.0.0.1] => {"failed": true}
msg: failed determining service state, possible typo of service name?

FATAL: all hosts have already failed -- aborting

Looks like it is still connected to LFs, since running:
`sudo dos2unix /vagrant/provisioning/roles/admin/files/mailhog_init`
from within the VM clears it.

Host machine: Windows 10
VirtualBox 5.0.3
vagrant 1.7.4

**Comment by ericmann** [comment]
Was this on a new, clean clone of HGV, or from an existing one?

**Comment by linuxbastard** [comment]
New clean clone.

**Comment by ericmann** [comment]
I've updated our `.gitattributes` file to force `mailhog_init` to have LF line endings (instead of the CRLF Windows default). Once this is merged in and deployed, clean clones will function as expected.
