### ISSUE TITLE
hostnames not added to hosts

### ISSUE THREAD

**Issue by mikkelbreum** [wpengine/hgv#251]
When I run vagrant up on a clean install of v1.4 it only adds hgv.test to my hosts file:

    ==> hgv: adding to (/etc/hosts) : 192.168.150.20  hgv.test
No other domains are added.

If I add custom domains via yml files in hgv_data/config/sites/ they are also not added to the hosts file
The custom sites get provisioned, and I can access them if I edit my hosts file manually.

I have manually added my custom domians plus the default domains:

    192.168.150.20 hgv.test
    192.168.150.20 admin.hgv.test
    192.168.150.20 hhvm.hgv.test
    192.168.150.20 php.hgv.test
    192.168.150.20 cache.hhvm.hgv.test
    192.168.150.20 cache.php.hgv.test

But these domains used to be added by default by the provisioner..

**Comment by ericmann** [comment]
@mikkelbreum do you have the [Vagrant Ghost](https://github.com/10up/vagrant-ghost) plugin installed?

**Comment by mikkelbreum** [comment]
No, I had the vagrant-hostsupdater installed.. wasn't aware that this dependency had changed.

**Comment by mikkelbreum** [comment]
it works now that Ghost is installed
