### ISSUE TITLE
dict object error

### ISSUE THREAD

**Issue by ajmorris** [wpengine/hgv#262]
I followed the following: 

Let HGV provision your WordPress for you.
Copy provisioning/default-install.yml to hgv_data/config/sites/foo.yml.
Change the enviro variable to the docroot of where your WordPress lives under [HGV directory]/hgv_data/sites/, ie ‘foo’. If the directory does not exist when provisioning is executed, it will be created and the latest stable version or WordPress installed.
Edit the domain lists to be the domain(s) you want setup for the WordPress residing in the Vagrant. Domains listed under hhvm_domains will be served by HHVM. Those listed under php_domains will be served by the PHP-FPM service. See the section in this documentation on PHP Selector for more.
If you did not install the vagrant-ghost plugin, you will need to manually add the domains to your host operating system’s host files. See the example above.

However I'm getting an interesting error: fatal: [127.0.0.1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'php_domains'", 'failed': True}

Can anyone tell me how to get my own domains working?

**Comment by zamoose** [comment]
Working with AJ on Slack, I think it's a problem in [provisioning/wordpress.yml](/wpengine/hgv/provisioning/wordpress.yml), line 12:

```
domains: "{{ wp.hhvm_domains }} + {{ wp.php_domains }}",
```

**Comment by zamoose** [comment]
Changing it to 

```
 domains: "{{ wp.hhvm_domains }} + {{ wp.php_domains|default('') }}",
```

clears up the error.

**Comment by ajmorris** [comment]
We thought restarting nginx would help but when we tried that it failed because of a test.

`vagrant@hgv:~$ sudo service nginx restart
 * Restarting nginx nginx                                                                                                                                                       nginx: [warn] conflicting server name "cache.r" on 0.0.0.0:80, ignored
nginx: [emerg] invalid server name or wildcard "cache.." on 0.0.0.0:80
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by markkelnar** [comment]
@ajmorris I just added to the develop branch a fix similar to what @zamoose suggested.  This should allow your YML file to not have the php_domains list.

If you are able to test this, can you confirm that it fixes your original error?  Thanks
