### ISSUE TITLE
Provisioning local-config.php

### ISSUE THREAD

**Issue by lgedeon** [wpengine/hgv#274]
I was trying to set up a multisite, and was getting the "Getting Started" page instead of the newly created sub-domain. So I tried "vagrant provision" to see if could get the domains I had added to hgv_data/config/sites/smallsites.yml to work. Could use good step by step directions for that, btw.

When I ran provision, it reset my hgv_data/sites/smallsites/local-config.php file. I thought the purpose of local-config.php was to keep stuff safe from ansible since it was modifying wp-config. Did I get that mixed up?

**Comment by markkelnar** [comment]
Hello @lgedeon , the local-config.php file is overwritten each time the 'vagrant provision' is run and kicks Ansible to do it's thing.  That is where HGV uses the DB creds we set for the WP.

Once the wp-config.php file is created once by Ansible, it will not create it again by 'vagrant provision' or Ansible.
