### ISSUE TITLE
Provision HTTPS/SSL site

### ISSUE THREAD

**Issue by jb510** [wpengine/hgv#276]
How does one provision a site to use HTTPS locally (assuming a self-signed cert).

I assumed I could just set site/home in local-config to https, but there doesn't seem to be a self signed cert available.  

I still assume I could ssh in and create it, update conf files, etc...  but before doing that thought I'd ask, is there another way and would it make sense to update provisioning to power this?

**Comment by markkelnar** [comment]
HGV doesn't run https or have anything in the provisioning to enable that in the Nginx config. 
That sounds like a fun feature to add.  If you do get around to adding it, let us know the details or submit a pull request with the code.  That would be awesome.

**Comment by jb510** [comment]
Thanks Mark, totally understand.  Unlikely I'll do that soon, but I'll keep it in mind.
