### ISSUE TITLE
Dropping database and importing from wpengine in 1.5

### ISSUE THREAD

**Issue by justinpage** [wpengine/hgv#280]
## Problem

After importing a database from wpengine into `wpe_hhvm`, `php.hgv.test` will display the homepage with broken styles within the theme. More specifically, it displays some info that would be found on `hgv.test` at the very top of `php.hgv.test`.
## Discussion

After provisioning the environment, we take ownership of `wp-content` folder through our own repository. This means getting rid of the original wp-content folder and cloning our `wp-content` folder. We then import a database from our wpengine production environment. We've done this before, with success, in the 1.3 build of hgv. 

We are curious if there is some sort of database change we need to make in order to correctly use a schema dump from wpengine.

If you need more info, I can spin up the 1.5 build again and provide some logs.

**Comment by raptor235** [comment]
What we've been noticing is that object cache is not cleared properly when the db is imported. You have issue a flush command to clear the cache after any manual db syncs. 

I'm not sure exactly how the db should be flushed but we've seen this in the past on the live environments where you do a 1 click deployment or sync a db and object caching is hold on to old data...
