### ISSUE TITLE
what's the ubuntu root password?

### ISSUE THREAD

**Issue by raptor235** [wpengine/hgv#283]
can't seem to find this anywhere

**Comment by zamoose** [comment]
Bart:
Why do you need the root password? The `vagrant` user has full sudo
access...

On Tue, Dec 15, 2015 at 9:51 AM, Bart Dabek <notifications@github.com>
wrote:

> can't seem to find this anywhere
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/283>.
>



-- 
-Doug

**Comment by andrew40** [comment]
You don't need the root password? what do you need it for?

**Comment by raptor235** [comment]
Sorry guys didn't get notifications of your replies... can't recall at this point.
