### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#29]
We should determine whether we want to stick to something rigorous, like Git-Flow, or handle things a bit more loosely. Also, we should determine whether we want a development/testing branch handled out of the main repository, to allow for unified testing.

Once we decide, we should definitely update [CONTRIBUTING.md](/wpengine/hgv/blob/master/CONTRIBUTING.md)

**Comment by michaelbeil** [comment]
Git-Flow seems like the best option along with a dev branch, of course.

**Comment by markkelnar** [comment]
I've gone circles on using a develop/dev branch or just using master as the target of pull requests.  

Here are some ideas ...
I've seen other projects that simply target all pull requests at master (VVV is one of thise), tags releases and follow semantic versioning (http://semver.org/).  Anything targeted at master is considered ready (not in progress) by the developer.  New contributors have a low bar of entry to targeting pull requests.

When are releases tagged you ask?  How often?  After what feature?  We can decide that frequency.

What about bugs found in releases?  Do we patch a tagged release?  How long do we support tagged releases?

If new code or a project requires a larger amount of work from multiple developers, we can create a feature branch for that larger work.

**Comment by zamoose** [comment]
@markkelnar VVV is actively considering opening a `develop` branch:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/534

**Comment by zamoose** [comment]
I definitely agree on following semver as a convention, though.

**Comment by zamoose** [comment]
I'd like to re-bump this for further consideration. Our primary parallel in this space, VVV, has recently moved to a development + feature branch model, with master being a repository for tagged releases.

**Comment by michaelbeil** [comment]
I too am for this gitflow workflow model, where we can have a dev branch, and feature branches that feed dev. Also worth considering are release branches. We create release branches from dev to work on iterating with our new feature branches and hotfix branches, which can look something like this: http://nvie.com/posts/a-successful-git-branching-model.

```
master
|---dev
      |---release/semver
           |---feature/name
           |---hotfix/name
```
