### ISSUE TITLE
wp-cli emitting warning message

### ISSUE THREAD

**Issue by asmartbear** [wpengine/hgv#31]
When I execute `wp`, I get a warning about deprecated comment style.

**Comment by markkelnar** [comment]
What is the text from the warning @asmartbear ?  Right @zamoose, the other comment style error was with xhprof.ini.  That's fixed.

**Comment by asmartbear** [comment]
Yes it's the xhprof.ini thing:

    $ vagrant ssh
    > Last login: Wed Jan 14 17:37:24 2015 from 10.0.2.2
    $ wp
    > PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/20-xhprof.ini on line 2 in Unknown on line 0

I tried `git pull` against mainline master but there were no changes, and I tried `vagrant provision` to ensure I have the latest config, so I'm not sure why I still don't have that fix?

Is there something else I should try to get that fixed configuration?

**Comment by asmartbear** [comment]
Operator error -- I was using an old version of the project!  Not a bug, thanks.
