### ISSUE TITLE
php7-fpm Job failed to start

### ISSUE THREAD

**Issue by tdamskov** [wpengine/hgv#316]
I'm trying to set up HGV on a Windows 10 machine.

On "vagrant up", I got the error referenced in issue #313. I attempted to fix the error by running the file through dos2unix, as mentioned before in the issue.

Continuing with provision, I'm now getting a new error:

==> hgv: RUNNING HANDLER [php-fpm : php7-fpm restart] ***********************************
==> hgv: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "stop php7-fpm ; start php7-fpm", "delta": "0:00:00.035312", "end": "2016-04-19 03:56:16.995306", "failed": true, "rc": 1, "start": "2016-04-19 03:56:16.959994", "stderr": "stop: Unknown instance: \nstart: Job failed to start", "stdout": "", "stdout_lines": [], "warnings": []}

`sudo service php7-fpm status` returns "php7-fpm stop/waiting" .. Trying to start it returns the same error, "Job failed to start".

On trying to access the various HGV links (e.g. http://admin.hgv.test/ ) just display the "welcome to nginx" page.

Any ideas how to solve this?

**Comment by kmg-yrabelo** [comment]
I'm getting a similar error to this one:
````==> vagrant: RUNNING HANDLER [php-fpm : php7-fpm restart] ***********************************
==> vagrant: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "stop php7-fpm ; start php7-fpm", "delta .013498", "end": "2016-04-20 18:02:20.752355", "failed": true, "rc": 1, "start": "2016-04-20 18:02:20.738857"
 "stop: Unknown instance: \nstart: Job failed to start", "stdout": "", "stdout_lines": [], "warnings": []}````

When I scroll up then I notice these are being skipped for some reason.

==> vagrant: TASK [php-fpm : Download PHP 7 deb] ********************************************
==> vagrant: **skipping: [127.0.0.1]**
==> vagrant:
==> vagrant: TASK [php-fpm : Install PHP 7 Nightly] *****************************************
==> vagrant: **skipping: [127.0.0.1]**

**Comment by tdamskov** [comment]
I can confirm kmg-yrabelo's notes. My log also shows:

==> hgv: TASK [php-fpm : Set PHP 7 bin as default] **************************************
**==> hgv: skipping: [127.0.0.1]**
==> hgv:
==> hgv: TASK [php-fpm : Set PHP 7 config as default] ***********************************
**==> hgv: skipping: [127.0.0.1]**
==> hgv:
==> hgv: TASK [php-fpm : Set PHP 7 ize as default] **************************************
**==> hgv: skipping: [127.0.0.1]**

**Comment by mswebshark360** [comment]
I found a solution to this, well, a workaround. For whatever reason, php7-fpm is not installing with the provisioning, or can't. I followed the instructions on [this page](https://www.23systems.net/2016/01/installing-php-5-6-x-7-0-x-ubuntu-14-04-virtualmin-5-0gpl-using-ppa/) to grab it from PPA, though stopping at the Virtualmin section on down as it didn't appear to apply to HGV... and then I also was sure to install php**7.0**-fpm, not just php7-fpm.  This ensures that it's on the server.  Then, you need to edit the following file on your local machine:

hgv\provisioning\roles\php-fpm\handlers\main.yml

> ---
> 
> - name: php5-fpm restart
>   command: restart php5-fpm
> 
> - name: php7.0-fpm restart
>   shell: stop php7.0-fpm ; start php7.0-fpm

Note that php7-fpm was changed in the three places it is called to php7.0-fpm.  Once you've done this you can run vagrant-provision again and you're good to go!

Hope this helps!  Not yet sure if this is just a temporary solution, but all is well on my end.

**Comment by dupski** [comment]
Rather than installing a different php-fpm, you can fix the already-installed one.

The issue is specific to Windows environments and due to windows line endings again. I was able to fix the issue by opening the following file:

```
hgv/provisioning/roles/php-fpm/templates/etc/php/checkconf
```

in Notepad++, then going to **Edit** -> **EOL Conversion** -> **UNIX/Mac OSX**, saving it, then re-running `vagrant provision`

**Comment by kmg-yrabelo** [comment]
@dupski ,

After following your instructions I was able to get it working. 

Thank you!

**Comment by smonksi** [comment]
@dupski great tip, this worked for me too. 

Such a little tweak, such a big impact :-)

Thanks!

**Comment by tdamskov** [comment]
Confirmed, the tip to fix the Windows line endings works perfectly. Closing the issue (although hoping this can be permanently fixed in the future).
