### ISSUE TITLE
Error Installing PHP 7

### ISSUE THREAD

**Issue by jeremylivingston** [wpengine/hgv#318]
I am receiving errors running `vagrant up` on a fresh box using this repository. I am running OS X El Capitan. Please see the log below:

```
==> hgv: TASK [php-fpm : Install PHP 7 Nightly] *****************************************
==> hgv: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'prepared'
==> hgv: fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TYi3p0/ansible_module_apt.py\", line 842, in <module>\n    main()\n  File \"/tmp/ansible_TYi3p0/ansible_module_apt.py\", line 798, in main\n    force=force_yes, dpkg_options=p['dpkg_options'])\n  File \"/tmp/ansible_TYi3p0/ansible_module_apt.py\", line 538, in install_deb\n    diff[\"prepared\"] += '\\n\\n' + out\nKeyError: 'prepared'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
==> hgv:
==> hgv: RUNNING HANDLER [hhvm : hhvm restart] ******************************************
==> hgv:
==> hgv: RUNNING HANDLER [php-fpm : php5-fpm restart] ***********************************
==> hgv:    to retry, use: --limit @/vagrant/provisioning/playbook.retry
==> hgv:
==> hgv: PLAY RECAP *********************************************************************
==> hgv: 127.0.0.1                  : ok=40   changed=32   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jeremylivingston** [comment]
For what it's worth, if I run `vagrant provision` after this step fails, I am able to successfully complete provisioning. On the first `vagrant up`, however, I consistently get failures at this step on a fresh install.

**Comment by cyberis** [comment]
I'd like to mention that on Macbook Pro (late 2013), OSX 10.11.4 (El Capitan) and following the instructions in the README.MD file I get exactly the same error as @jeremylivingston and rerunning the provisioning step succeeds like like it does for @jeremylivingston.

**Comment by nfuller52** [comment]
@jeremylivingston and @cyberis this is actually a bug in the ansible apt core module with ansible version 2.1. If it's giving you issues, fallback to ansible 1.9. You can do that by editing bin/hgv-init.sh and changing line 38 from `add-apt-repository -y ppa:ansible` to `add-apt-repository -y ppa:ansible/ansible-1.9`

**Comment by storypixel** [comment]
Same issue

**Comment by smonksi** [comment]
@nfuller changing back to ansible 1.9 did the trick. Thanks.

**Comment by chrisbanm** [comment]
I was also having the same problem and when I just tried to run vagrant provision again, it LOOKED like it succeeded but it really didn't since it simply skipped the nightly PHP7 set as it though that step was done. So I backed off Ansible to the 1.9 version as @nfuller52 suggested and all was good. I hope that gets fixed in Ansible or a better workaround in hgv than simply reverting to an older version of Ansible but for the moment it got me a working HGV environment on Ubuntu 16.04LTS (_I had the same problem when installing on Windows 7 and OS X 10.11.4 so it's not a host platform dependent problem_).

**Comment by storypixel** [comment]
ansible 1.9 did the trick for me as well, i'm eager to undo this hack when ansible is fixed or a workaround is baked into hgv

**Comment by ehoanshelt** [comment]
@jeremylivingston Can you try testing this again with the latest master branch? Please let me know if you are experiencing the same issue!

**Comment by ehoanshelt** [comment]
Due to not being able to replicate this issue anymore, I'm closing this out. Please feel free to re-open!
