### ISSUE TITLE
FAIL on Vagrant Up - Latest Release

### ISSUE THREAD

**Issue by andrew40** [wpengine/hgv#325]
Not 

Getting a fail on vagrant up --provision on the latest install. It seems to be an authentication error? 

`==> hgv: TASK [percona : Install Percona server] ****************************************
==> hgv: fatal: [127.0.0.1]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'percona-server-server-5.6'' failed: E: There are problems and -y was used without --force-yes\n", "stderr": "E: There are problems and -y was used without --force-yes\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following extra packages will be installed:\n  libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1\n  percona-server-client-5.6 percona-server-common-5.6\nSuggested packages:\n  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl\n  libsql-statement-perl tinyca\nThe following NEW packages will be installed:\n  libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1\n  percona-server-client-5.6 percona-server-common-5.6\n  percona-server-server-5.6\n0 upgraded, 7 newly installed, 0 to remove and 18 not upgraded.\nNeed to get 14.3 MB of archives.\nAfter this operation, 139 MB of additional disk space will be used.\nWARNING: The following packages cannot be authenticated!\n  percona-server-common-5.6 libperconaserverclient18.1\n  percona-server-client-5.6 percona-server-server-5.6\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following extra packages will be installed:", "  libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1", "  percona-server-client-5.6 percona-server-common-5.6", "Suggested packages:", "  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl", "  libsql-statement-perl tinyca", "The following NEW packages will be installed:", "  libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1", "  percona-server-client-5.6 percona-server-common-5.6", "  percona-server-server-5.6", "0 upgraded, 7 newly installed, 0 to remove and 18 not upgraded.", "Need to get 14.3 MB of archives.", "After this operation, 139 MB of additional disk space will be used.", "WARNING: The following packages cannot be authenticated!", "  percona-server-common-5.6 libperconaserverclient18.1", "  percona-server-client-5.6 percona-server-server-5.6"]}
==> hgv:`

**Comment by andrew40** [comment]
I think #319 sums it all up..

**Comment by adambreen** [comment]
I was able to resolve this particular problem by changing line 20 in /hgv/provisioning/roles/percona/tasks/main.yml 

from

`apt: name=percona-server-server-5.6 state=present`

to 

`apt: name=percona-server-server-5.6 state=present force=yes`

**Comment by adambreen** [comment]
@andrew40 that really sucks! Thanks for the info, as I've just burned a day and a half getting things running. @markkelnar @stephen-lin @zamoose @marshalllarson would you please either update your public webpages and this repo to let folks know that you're not maintaining it further, or (even better) cheer @andrew40 and me up by letting us know that the info in https://github.com/wpengine/hgv/issues/319 is incorrect?

**Comment by andrew40** [comment]
Unfortunately that didn't work for me, and all I get is syntax errors for that file i edited, even though i can't see anything wrong?

` ---
- name: ensure /etc/mysql
  file: path=/etc/mysql state=directory owner=root group=root mode=0755
  tags: [ 'percona', 'database' ]

- name: ensure /etc/mysql/my.cnf ...
  template: src=etc/mysql/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify:
    - mysql restart

- name: Install Percona GPG key
  apt_key: file=/vagrant/provisioning/roles/percona/templates/percona-gpg-key state=present
  tags: [ 'percona', 'database' ]

- name: Enable Percona repo
  apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} main' state=present
  tags: [ 'percona', 'database' ]

- name: Install Percona server
  apt: name=percona-server-server-5.6 state=present force=yes
  notify:
    - update-rc mysql
    - mysql restart
  tags: [ 'percona', 'database' ]

- name: Install Percona client
  apt: name=percona-server-client-5.6 state=present
  tags: [ 'percona', 'database' ]

- name: Grant root user access
  mysql_user:
    name: root
    priv: "*.*:ALL"
    host: "%"
    password: ""
    state: present
  tags: [ 'percona', 'database' ]
#- name: Ensure Percona is running
#  service: name=mysql state=started`

**Comment by rdela** [comment]
Anyone struggling to get HGV ```vagrant up```
may want to take a look at #326.
Repeating
```vagrant provision```
with the 2 changes in commit above/#326, 1 from @adambreen [above](https://github.com/wpengine/hgv/issues/325#issuecomment-256828142) (thanks), got me through provision.

**Comment by isabisa** [comment]
Thank you @adambreen and @rdela that helped!

**Comment by adambreen** [comment]
Hey folks, fwiw, after burning a LOT of time struggling with HGV, I've moved to [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV), and I'm having a much better experience. As you've probably noticed, HGV just doesn't seem to be actively maintained any more :(

In [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV), what you've learned about Ansible Playbooks etc. will still be very handy if you also make the switch. Plus they have very straightforward documentation (but make sure you do EVERYTHING they say, including the required vagrant plugins!).

**Comment by ehoanshelt** [comment]
This issue appears to be resolved with https://github.com/wpengine/hgv/pull/326 which is now merged into master. I can't seem to replicate this issue anymore. I'm going to close this issue for now but please feel free to re-open if the issue pops up again

**Comment by dotid** [comment]
I had same problem and solved by:

sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 8507EFA5
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8507EFA5
sudo apt-key update
sudo apt-get update
