### ISSUE TITLE
Provisioning failing on PHP_CodeSniffer

### ISSUE THREAD

**Issue by jshwlkr** [wpengine/hgv#327]
Clean install on OSX 10.11.6, keep getting this error:

```
==> hgv: TASK [php-fpm : Install PEAR modules] ******************************************
==> hgv: failed: [127.0.0.1] (item=PHP_CodeSniffer) => {"changed": true, "cmd": ["pear", "install", 
"PHP_CodeSniffer"], "delta": "0:00:00.298889", "end": "2016-11-07 16:16:38.166244", "failed": true,
 "failed_when_result": true, "item": "PHP_CodeSniffer", "rc": 1, "start": "2016-11-07 16:16:37.867355",
"stderr": "", "stdout": "No releases for package \"pear/PHP_CodeSniffer\" exist\ninstall failed", 
"stdout_lines": ["No releases for package \"pear/PHP_CodeSniffer\" exist", "install failed"], 
"warnings": []}
```

**Comment by andrew40** [comment]
Might want to check out #319

**Comment by jshwlkr** [comment]
![teamcoco-conan-obrien-kevin-hart-3oz8xMbKLAkRLHYNgI](https://camo.githubusercontent.com/ab00064cffe29c250c1f0b3a3145eb0f6b03fe4a/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f336f7a38784d624b4c416b524c48594e67492f67697068792e676966>)

**Comment by andrew40** [comment]
That lifted my day!!

Have a look at https://github.com/roots/trellis

**Comment by jasondemeuse** [comment]
@jshwlkr  I was able to get rid of this error by adding the `pear clear-cache`, `pear update-channels`, and `pear upgrade` commands to the main.yml just before the `Install PEAR modules` task. This combined with fixes from the other pull requests and I was able to get everything running.

Still going to need to find a different route eventually (like @andrew40 mentioned with trellis) but if you're like me and needed to get this running today temporarily, it should be enough. If it helps I have a fork of this with the fixes I mentioned.

**Comment by andrew40** [comment]
If your using this because your hosting on WPEngine you need to find another way, as they are concentrating on PHP7.0 now and not HHVM, so your vagrant will not be replicating the live host.

**Comment by ehoanshelt** [comment]
@jshwlkr I currently can't replicate this on my machine. Can you please try this again with the latest master branch to see if you are running into the same issue? If so, let me know and I'll get some dev time in for this.

**Comment by jshwlkr** [comment]
@ehoanshelt I don't seem to be having the error anymore!

**Comment by ehoanshelt** [comment]
Awesome! Thanks for the feedback! I'll close this out for now but please let us know if you run into anything else!
