### ISSUE TITLE
Provision Error

### ISSUE THREAD

**Issue by matthewsuan** [wpengine/hgv#328]
Hi,

I encountered an error: Warning: Couldn't find 'default_plugins' in the WordPress.org plugin directory.\nError: No plugins installed.

This happens every time I do `vagrant provision` and after that, the newly added site will just default to hgv homepage.

Thanks.

**Comment by andrew40** [comment]
See #319

**Comment by ehoanshelt** [comment]
This issue has now been fixed with https://github.com/wpengine/hgv/pull/332. Closing out
