### ISSUE TITLE
Percona server installation error

### ISSUE THREAD

**Issue by skadzielawa** [wpengine/hgv#329]
I can't successfully execute 'vagrant up' command for the first time. Percona server installation failed...
<img width="1283" alt="screenshot 2017-01-10 12 00 40" src="https://cloud.githubusercontent.com/assets/8742028/21803916/9e083074-d72c-11e6-8ec6-98d73c60bf61.png">

**Comment by ethansmith** [comment]
See #326 . The two changes suggested fixed this issue for me.

**Comment by ehoanshelt** [comment]
This has now been fixed with https://github.com/wpengine/hgv/pull/326. Closing this issue out!
