### ISSUE TITLE
failed provision on #332

### ISSUE THREAD

**Issue by andrew40** [wpengine/hgv#335]
Getting this error message on a recent provision from the dev branch today #332 

`TASK [php-fpm : Download PHP 7 deb] ********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create temporary content file: The read operation timed out"}

**Comment by ehoanshelt** [comment]
@andrew40 Talking to the devs about this now. Thanks for reporting the issue!

**Comment by ehoanshelt** [comment]
@andrew40 We believe we have fixed this. Please test again and let us know if you find any other issues!
