### ISSUE TITLE
WP-CLI fails if code uses PHP 5.6+ features

### ISSUE THREAD

**Issue by morganestes** [wpengine/hgv#358]
Since the PHP version in the CLI is 5.5, when I run `wp` commands on my repo that contains code specific to PHP 5.6, the wp-cli command fails with an error. Since WP Engine uses PHP 5.6 as the version for new installs, then we should be using 5.6 for wp-cli as well, no?

In my case, I'm using `use function` in a plugin, which isn't okay in PHP 5.5 so it throws an error. I can pass `--skip-plugins` to work around some of that, but that's not good if I'm trying to work with plugins or rewrites.

**Comment by markkelnar** [comment]
Removed PHP5.5 as part of https://github.com/wpengine/hgv/pull/371.  This might fix this issue.
