### ISSUE TITLE
Install PECL modules Ansible Task fails on machine provisioning

### ISSUE THREAD

**Issue by chrisbanm** [wpengine/hgv#364]
When I tried to create a new box (vagrant up without an existing box) I get a failure during the php-frm Install PECL modules task:

==> hgv: TASK [php-fpm : Install PECL modules] ******************************************
==> hgv: failed: [127.0.0.1] (item=yaml) => {"changed": true, "cmd": ["pecl", "install", "yaml"], "delta": "0:00:00.594062", "end": "2017-08-03 18:45:17.054558", "failed": true, "failed_when_result": true, "item": "yaml", "rc": 1, "start": "2017-08-03 18:45:16.460496", "stderr": "", "stderr_lines": [], "stdout": "pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.21\nNo valid packages found\ninstall failed", "stdout_lines": ["pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.21", "No valid packages found", "install failed"]}

Looks like pecl/yaml dependency is failing?

This appears to be a different issue than #361.

**Comment by jeffpamer** [comment]
Just ran into this as well.

**Comment by gabe-connolly** [comment]
Same issue here as well.

```
==> hgv_2: TASK [php-fpm : Install PECL modules] ******************************************
==> hgv_2: failed: [127.0.0.1] (item=yaml) => {"changed": true, "cmd": ["pecl", "install", "yaml"], "delta": "0:00:00.502450", "end": "2017-08-04 16:27:24.035799", "failed": true, "failed_when_result": true, "item": "yaml", "rc": 1, "start": "2017-08-04 16:27:23.533349", "stderr": "", "stderr_lines": [], "stdout": "pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.21\nNo valid packages found\ninstall failed", "stdout_lines": ["pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.21", "No valid packages found", "install failed"]}
==> hgv_2: 
==> hgv_2: RUNNING HANDLER [hhvm : hhvm restart] ******************************************
==> hgv_2: 	to retry, use: --limit @/vagrant/provisioning/playbook.retry
==> hgv_2: 
==> hgv_2: PLAY RECAP *********************************************************************
==> hgv_2: 127.0.0.1                  : ok=28   changed=25   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

>

**Comment by gabe-connolly** [comment]
I believe this problem is coming from PECL trying to install the 2.0.2 version of the yaml module:

https://pecl.php.net/package/yaml

This version requres PHP 7+, which was not the default in my local environment.  By version locking the yaml plugin to 1.3.1 (at least for now) you should be able to get your provision to run correctly:

https://gist.github.com/gabe-connolly/e8dc0da53dca9ebaad8c741a874e49f9

```
# File: provisioning/roles/php-fpm/tasks/main.yml
- name: Install PECL modules
  command: pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "'already installed' not in pecl_result.stdout and 'completed successfully' not in pecl_result.stdout"
  with_items:
    - yaml-1.3.1
```

**Comment by markkelnar** [comment]
This should be fixed as part of https://github.com/wpengine/hgv/pull/371

**Comment by electricbrick** [comment]
I'm still experiencing this issue, even after #371.
