### ISSUE TITLE
No valid packages found

### ISSUE THREAD

**Issue by yanickvanbarneveld** [wpengine/hgv#366]
When trying to run "vagrant up". I am retrieving this error after a few minutes.

`==> hgv: TASK [php-fpm : Install PECL modules] ******************************************
==> hgv: failed: [127.0.0.1] (item=yaml) => {"changed": true, "cmd": ["pecl", "install", "yaml"], "delta": "0:00:01.648000", "end": "2017-09-01 13:13:18.383974", "failed": true, "failed_when_result": true, "item": "yaml", "rc": 1, "start": "2017-09-01 13:13:16.735974", "stderr": "", "stderr_lines": [], "stdout": "pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.22\nNo valid packages found\ninstall failed", "stdout_lines": ["pecl/yaml requires PHP (version >= 7.0.0-dev), installed version is 5.5.9-1ubuntu4.22", "No valid packages found", "install failed"]}
==> hgv: 
==> hgv: RUNNING HANDLER [hhvm : hhvm restart] ******************************************
==> hgv: 	to retry, use: --limit @/vagrant/provisioning/playbook.retry
==> hgv: 
==> hgv: PLAY RECAP *********************************************************************
==> hgv: 127.0.0.1                  : ok=28   changed=25   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

Someone knows how to fix this or what the problem is?

**Comment by andrewsavikas** [comment]
I tried the solution in https://github.com/wpengine/hgv/issues/364 and that fixed this issue (though the install still failed downstream). To be explicit: from the hgv directory, navigate to provisioning/roles/php-fpm/tasks/main.yml and find the section about PECL and yaml and update it as described in that issue.

**Comment by markkelnar** [comment]
This is because of PHP5.5 package dependencies.  PHP5.5 is removed in https://github.com/wpengine/hgv/pull/371.  This should allow the vagrant provisioning to continue.
