### ISSUE TITLE
Failed to fetch http://repo.varnish-cache.org/ubuntu/dists/trusty/varnish-3.0/binary-amd64

### ISSUE THREAD

**Issue by andrewsavikas** [wpengine/hgv#370]
`vagrant up` fails with the following message:

`==> hgv: fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vw5O7Q/ansible_module_apt_repository.py\", line 565, in <module>\n    main()\n  File \"/tmp/ansible_vw5O7Q/ansible_module_apt_repository.py\", line 553, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:GPG error: http://repo.percona.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9334A25F8507EFA5, W:GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C, W:Failed to fetch http://repo.varnish-cache.org/ubuntu/dists/trusty/varnish-3.0/binary-amd64/Packages  410  repo\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}`

I am seeing an actual thing at http://hgv.test, but it's just a generic nginx welcome screen (ditto when clicking on the other URLs that are supposed to be other things like `http://php.hgv.test/`).

**Comment by markkelnar** [comment]
This is fixed with https://github.com/wpengine/hgv/pull/369
