### ISSUE TITLE
FYI: WP Engine is no longer maintaining or supporting this project

### ISSUE THREAD

**Issue by peterhartree** [wpengine/hgv#377]
I confirmed this via live chat and phone support today.

Weirdly it seems like WP Engine don't have an official recommendation on how to setup a local development environment at the moment.

I'm currently trialling [Local by Flywheel](https://local.getflywheel.com). It seems promising.

**Comment by octalmage** [comment]
Hi @peterhartree, I've got a PR up to make sure the readme is updated: 

https://github.com/wpengine/hgv/pull/378

We are working on something in this space so stay tuned! If you want you can shoot me an email at stallings@wpengine.com and I can reach out to you when we have more information available.
