### ISSUE TITLE
Installation caused an error, webserver won't start.

### ISSUE THREAD

**Issue by georgestephanis** [wpengine/hgv#39]
First `vagrant up` resulted in this as the tail end of the messages:

```
==> hgv: TASK: [hhvm | Enable HHVM repo] ***********************************************
==> hgv: failed: [127.0.0.1] => {"failed": true, "item": "", "parsed": false}
==> hgv: invalid output was: SUDO-SUCCESS-igfchwxnhnnvujaqrenfwutzmrgoqbiw
==> hgv: Traceback (most recent call last):
==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1421267187.88-125407138722026/apt_repository", line 1510, in <module>
==> hgv:     main()
==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1421267187.88-125407138722026/apt_repository", line 408, in main
==> hgv:     cache.update()
==> hgv:   File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
==> hgv:     raise FetchFailedException(e)
==> hgv: apt.cache.FetchFailedException: W:Failed to fetch bzip2:/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en  Hash Sum mismatch
==> hgv: , E:Some index files failed to download. They have been ignored, or old ones used instead.
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ********************************************************************
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=14   changed=13   unreachable=0    failed=1
~/code/hgv $
```

When it completed, hosts entries were created, I could `vagrant ssh` in just fine, but no response on port 80.  Ping worked fine.

Random fluke and I should try destroying and reinstalling?

**Comment by georgestephanis** [comment]
And I'm running OSX Yosemite locally, and have never had any problems with VVV (which is also running)

**Comment by zamoose** [comment]
@georgestephanis Sounds like a network disruption means one of the apt fetches didn't complete correctly. A destroy/up cycle may catch it, or you could try running `vagrant provision` and monitor it to see whether it completes.

**Comment by zamoose** [comment]
(Either way, let me know the results -- that's definitely not somewhere we've seen it fall down in the past.)

**Comment by georgestephanis** [comment]
I am running getcloak as a vpn as I'm on a public wifi at my coworking space currently -- destroy/up'ing now.

**Comment by georgestephanis** [comment]
I'm thinking it was an initial goof.  The destroy/up has me past the `hhvm | Enable HHVM repo` step currently, on to `hhvm | Install HHVM` and still going.  I'll reopen if it errors again, but it seems good.

Thanks!

**Comment by zamoose** [comment]
I've seen circumstances where apt is just too willing to give up on downloading repo headers/metadata, particularly if a mirror or two is out of sync with the upstreams, alas.
