### ISSUE TITLE
Implement Ansible Coding/Scripting Standards

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#4]
Here's a good place to start:

https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions

We should document and then abide by said standards.

**Comment by markkelnar** [comment]
That's an interesting convention.  I'm not sure I see enough in there that applies to our uses.  For example, when we use apt_key to do we reference the remote url for the key or save it to a file in the project?  And what naming and directory structure do we follow under the templates/ for a role that matches the target location of the file?  (just to name a few).

**Comment by rcjohnson** [comment]
Given that there's not a clear standard for Ansible coding conventions, I think this can wait for now.
