### ISSUE TITLE
vagrant plugin install vagrant-hostsupdater error on Mac

### ISSUE THREAD

**Issue by dbwpe** [wpengine/hgv#40]
On OSX 10.9.5 - ruby v2.0.0

I set my hosts file to get around this, but I got this error trying to install vagrant-hostsupdater:

```
$ vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.5'` succeeds before bundling.
```

If anyone else runs into this issue, it's easy to get the server's IP after `vagrant up` like so:

```
vagrant ssh
ifconfig | grep -A1 eth1 | egrep -o "addr\S+"
```

Then take that IP and put it in /etc/hosts roundabouts like this:

```
<ip.add.re.ss> hgv.dev admin.hgv.dev hhvm.hgv.dev php.hgv.dev cache.hhvm.hgv.dev cache.php.hgv.dev
```

**Comment by zamoose** [comment]
We should document the IP address so you don't have to go hunting. 

--
Doug Stewart

**Comment by dbwpe** [comment]
That would be nice, but it's hard to guess what it'll be before it's set up in VirtualBox, because DHCP methinks.  And you can't visit the local help page that does show it if you don't have either the IP or hosts file set with the IP.

**Comment by zamoose** [comment]
Nope, it's set statically -- 192.168.150.20. 

--
Doug Stewart

**Comment by dbwpe** [comment]
Well then, knowing that would indeed have made things a bit easier. :P

**Comment by zamoose** [comment]
As I said, we really should document that somewhere. *grin* 

--
Doug Stewart

**Comment by dbwpe** [comment]
What if there's already a machine on the network with that IP?
Also there could feasibly be more than one person on a network running this vagrant.
Would having the same IP pose a problem?

**Comment by zamoose** [comment]
By default, this shouldn't cause any issues between machines, as we utilize Vagrant's [private networking capabilities](https://docs.vagrantup.com/v2/networking/private_network.html). This prevents those addresses from affecting any machines other than the local one.

**Comment by michaelbeil** [comment]
documenting the IP would be gladly welcomed.

**Comment by zamoose** [comment]
I just realized we do, @michaelbeil: https://github.com/wpengine/hgv#next-steps

**Comment by michaelbeil** [comment]
I just saw this ;P ... https://github.com/wpengine/hgv/blame/master/README.md#L74

**Comment by dbwpe** [comment]
Sorry about the runaround guys!  I was following the instructions [here](http://wpengine.com/mercury/how-to-start/) from the internal email we got, rather than the github readme.  I'll get in touch with someone internally to update our doc.

Thanks for the consideration!
