### ISSUE TITLE
MariaDB 10.0

### ISSUE THREAD

**Issue by ottok** [wpengine/hgv#42]
Why is MySQL 5.6 (Percona version) chosen as the database, why not MariaDB 10.0? Could MariaDB 10.0 at least be as an option?

**Comment by markkelnar** [comment]
Great idea to have MariaDB as an option to this vagrant for people that prefer that instead.  

MySQL Percona is used in this vagrant because it's what we use here at WP Engine and are most familiar with for WordPress.

**Comment by zamoose** [comment]
Otto:
What's the reason for wanting MariaDB vs. upstream MySQL/Percona?

**Comment by ottok** [comment]
Here is a very recent article: http://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql
Percona is an improvement over Oracle MySQL but I think MariaDB 10.0 is the best option at the moment.

**Comment by zamoose** [comment]
Otto:
Thanks for that. Well worth considering as an option, though I don't know if it's something we want to tackle in the next version.

**Comment by rcjohnson** [comment]
Adding support for Maria is still not a priority. If someone added that in a fork and wanted to contribute that back up to HGV we would absolutely consider including it, but for the time being I'm going to close this issue to clean up the issues backlog.
