### ISSUE TITLE
P3 (plugin profiler) doesn't work with opcode caches installed

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#43]
Every run generates a report in which P3 is shown to use 100% of the plugin render time. Obviously, this makes it useless.

We either need an on-the-fly way to disable opcode caching for P3 runs or we should probably drop its inclusion in HGV.

**Comment by markkelnar** [comment]
Stop installing P3 with this code change https://github.com/wpengine/hgv/pull/107 .  Will still exist where we've enabled the plugin so far, but I think that's ok.
