### ISSUE TITLE
It's possible to have one Hgv instance and multiple sites?

### ISSUE THREAD

**Issue by iamntz** [wpengine/hgv#44]
I was wondering if there is a quick way of adding a new subdomain, e.g. `foo.hgv.dev` and creating a new DB for that subdomain as well (with or without installing WP, this is less important)

Thanks!

**Comment by zamoose** [comment]
Quick? Not quite yet. It's definitely a feature request that folks have.

**Comment by iamntz** [comment]
Ok, if not quick... there is a way that doesn't imply changing the provisioning? :)

**Comment by zamoose** [comment]
Easiest way to do so at this point:

1. Copy one of the existing Nginx configuration files in `/etc/nginx/sites-available` and edit it to fit your desired hostname, upstream PHP processor (HHVM, PHP-FPM), etc.
2. Symlink that new config file to `/etc/nginx/sites-enabled`
3. Create the new docroot under `/nas/wp/www/sites/` and make it match your docroot as specified in step 1.
4. Make sure everything in the docroot belongs to user `www-data` and group `www-data` so the web server can see it.
5. Provision a new database using your tool of choice (MySQL CLI, phpMyAdmin, etc.)
6. Add the new hostname[s] to your `/etc/hosts` file by hand.
7. Restart the Nginx process with `sudo service nginx restart`.
8. Bob's your uncle.

The new docroot should be directly available to your host OS via the `hgv_data` shared folder, so you can drag and drop whatever you need to into that folder.

**Comment by iamntz** [comment]
![](http://img.iamntz.com/1/mog.gif)

Alright, thanks. Let's see if I succeed or not (and if I can automate this in a way or another)

**Comment by zamoose** [comment]
@iamntz we're looking to make it easier, I swear. *grin*

**Comment by michaelbeil** [comment]
@iamntz, i'm sure @zamoose is readying the pipes with Uncle Bob.

**Comment by msouden** [comment]
Bumpity Bump bump.

I've been using this with VVV:
https://github.com/aliso/vvv-site-wizard

But, being that my client's WPEngine-based, I needed to match stacks. I'm no Vagrant ninja - but in case you guys working on getting a site-automation script are looking for resources, the bottom of this page has 6 or 8 different ones that've been made for VVV:

https://github.com/varying-vagrant-vagrants/vvv/wiki/Auto-site-Setup

Cheers,
Matt

**Comment by zamoose** [comment]
Hey @msouden:
Thanks for the feedback! I'm working on a feature branch at the moment and hope to have a PR ready for review soon. This will be a bit of an iterative process and @markkelnar, @stephen-lin, and I have been having discussions on what this would ideally look like.

**Comment by jb510** [comment]
I may have just opened a duplicate #84

If you want to go the way of aliso's site wizard, check out @bradp's newer Varible VVV [https://github.com/bradp/vv] which is WAY better and more sophisticated.  It hard codes a few things that keeps it from working with HGV, but I've started a fork to make web root variable (still needs a LOT of work to be functional) https://github.com/jb510/vv/commit/dc7f22973ec71a604b5fc0bd5cdad245a54d2226

**Comment by bradp** [comment]
I'd be totally down with adding HGV suppor tto VV, the only thing I'd need is a way to do the things inside of the VM. VVV does it by scanning the directories in side of the sites folder, and then executing any vvv-init.sh files present.

If something similar was added to HGV, we could easily get auto-site setup going with VV.

**Comment by zamoose** [comment]
@bradp Notionally, there will be two YAML files of similar (identical?) format that will govern the custom sites being generated. One will be provided with HGV, while the other is optional and will live in `hgv_data/`. Generating and parsing that YAML file will be where the action's at.

**Comment by sc0ttkclark** [comment]
+1 on this dawg

![Dawg](http://sc0tt.me/image/3a30422L0A10/Screen%20Shot%202015-04-26%20at%201.17.14%20PM.png)

**Comment by JasonTheAdams** [comment]
Here's a question for anyone else trying to do it manually in the meantime: How and where is it configured that a site uses hhvm or php? I've looked at the php-php.conf and hhvm-hhvm.conf files and they're identical, and it looks like the hhvm.conf is intercepting and passing all .hh/.php files to hhvm. But, presumably, php.hgv.dev isn't using hhvm?

Any help with that would be very appreciated! Other than that, I think adding a site manually is pretty painless.

**Comment by markkelnar** [comment]
Functionally available by PR #154 with introduction of custom YML files containing WP docroot and domain lists.  Once we finish documentation, this will be fully complete.  

The quick usage is to 
1. copy provisioning/default-install.yml to hgv_data/config/foo.yml.  
2. Change the enviro variable to the docroot of where your WP lives under hgv_data/sites/, ie 'foo'.  
3. Edit the domain lists to be the domain(s) you want setup for the WP residing in the Vagrant.

**Comment by jb510** [comment]
@markkelnar & @boogah this works great, thank you!

**Comment by boogah** [comment]
:+1: 

Glad to hear it @jb510!
