### ISSUE TITLE
Docs page text block formatting

### ISSUE THREAD

**Issue by michaelbeil** [wpengine/hgv#46]
Just a heads up on a few weird doc blocks over on hgv.dev.

![hgv dev off](https://cloud.githubusercontent.com/assets/4752949/5765666/f6c82dca-9cc0-11e4-8f42-3c3db7dd4a32.png)
![screen shot 2015-01-15 at 2 11 48 pm](https://cloud.githubusercontent.com/assets/4752949/5765667/f6d1323a-9cc0-11e4-9dca-209183867171.png)

**Comment by zamoose** [comment]
That's the default way Flatdoc handles blockquotes and code blocks. ()
http://ricostacruz.com/flatdoc/) I'm not really in love with it, frankly.

On Thu, Jan 15, 2015 at 3:16 PM, Michael Beil <notifications@github.com>
wrote:

> Just a heads up on a few weird doc blocks over on hgv.dev.
>
> [image: hgv dev off]
> <https://cloud.githubusercontent.com/assets/4752949/5765666/f6c82dca-9cc0-11e4-8f42-3c3db7dd4a32.png>
> [image: screen shot 2015-01-15 at 2 11 48 pm]
> <https://cloud.githubusercontent.com/assets/4752949/5765667/f6d1323a-9cc0-11e4-9dca-209183867171.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/46>.
>



-- 
-Doug

**Comment by michaelbeil** [comment]
oh suck. well, oh well.

**Comment by zamoose** [comment]
Fixed in #103.

Leaving closed.
