### ISSUE TITLE
Investigate Daux.io as replacement for Flatdoc

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#47]
It's nicer and would allow us to make a lot of different docs available locally:

http://daux.io/

**Comment by michaelbeil** [comment]
that's slick.

**Comment by zamoose** [comment]
Flat doc was definitely sufficient for MVP purposes but it's kind of a bear to configure and the look is a little off, as you discovered. 

--
Doug Stewart

**Comment by michaelbeil** [comment]
i think this should resolve #46.

**Comment by zamoose** [comment]
Closing this out, as the need for it just isn't there to justify the effort.
