### ISSUE TITLE
SSH forward agent into the Vagrant

### ISSUE THREAD

**Issue by markkelnar** [wpengine/hgv#56]
Enable ssh forward agent when the vagrant is loaded so that native ssh keys can be used within the vagrant.  This needs to be done to make that happen along with ssh-add confirmation in the native system.

See documentation here
https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html

**Comment by zamoose** [comment]
Quick question here:
What's the use case? Are we looking to enable users other than `vagrant` internal to the machine, or...?

**Comment by markkelnar** [comment]
The use case is to be able to interface with github as my own github user using the ssh keys that I've already setup on my Mac.  Then I can checkout repos from github and push up code from within the vagrant.

ssh -T git@github.com

**Comment by zamoose** [comment]
Ahh! Brain's not working right tonight. I'm on board.
