### ISSUE TITLE
Serverspec-based CI testing for HGV changes?

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#60]
[Serverspec](http://serverspec.org/) is a nifty idea. Perhaps a bit overkill in the short run, but if folks start using HGV in production sorts of scenarios, it could be really good to automatedly test for regressions, etc.

**PROS**
* System config assurance across multiple environments (Vagrant, virtualization providers, etc.)

**CONS**
* Complicated
* I'll have to learn more Ruby.

**Comment by michaelbeil** [comment]
it should only take a week to learn ruby. wait ...

**Comment by zamoose** [comment]
[VVV 486](https://github.com/Varying-Vagrant-Vagrants/VVV/pull/486) shows real progress on this issue.

**Comment by miya0001** [comment]
I wrote tests with serverspec.
But I haven't figured out how to CI. :wink:
