### ISSUE TITLE
Importing big SQL file

### ISSUE THREAD

**Issue by iamntz** [wpengine/hgv#68]
Hi guys. I'm trying to import a fairly big sql file (~400Mb) and I'm trying to do this by connecting to ssh then run `mysql -u root wpe_hhvm < sql-dump.sql`. What I'm getting is this:

> ERROR 1118 (42000) at line 58648: Row size too large

I followed various SO questions (e.g. [this](http://stackoverflow.com/questions/25299370/mysql-error-1118-row-size-too-large-when-restoring-django-mailer-database)) without any luck on making it work.

Any hints? Thanks!

(also, at least on Windows hosts, phpmyadmin doesn't work because of a directory has writing permissions, but I guess that's not _that_ important)

**Comment by zamoose** [comment]
@iamntz:
Please do submit an issue in regards to the phpMyAdmin issue -- I'd definitely be interested in knowing what you're encountering.

As to the row size, we'll have to take a look. We do use Percona as opposed to upstream MySQL, though I don't think that should necessarily have a dramatic effect one way or the other.

**Comment by iamntz** [comment]
The whole message is this: 

> ERROR 1118 (42000) at line 58648: Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.

**Comment by iamntz** [comment]
The manual way of fixing this is this:

1. Stop sql server by running `sudo /etc/init.d/mysql stop`
1. `sudo vim /etc/mysql/my.cnf`
1. Search for `max_allowed_packet` and set it to 64M
1. At the end of `[mysqld]` section, add this:

```
innodb_file_per_table
innodb_file_format = Barracuda
innodb_log_file_size = 256M
```

1. Delete existing log files by running `sudo rm /var/lib/mysql/ib_logfile*`
1. Start sql server by running `sudo /etc/init.d/mysql start`

See? Easy! :dancer:
