### ISSUE TITLE
Windows and phpMyAdmin error

### ISSUE THREAD

**Issue by iamntz** [wpengine/hgv#69]
> phpMyAdmin - Error
> Wrong permissions on configuration file, should not be world writable!

Most likely the problem is that shared folder don't also share their permissions.

**Comment by markkelnar** [comment]
Hello @iamntz, when do you encounter this error?  Are you able to use phpMyAdmin at all?

**Comment by iamntz** [comment]
When i try to access phpMyAdmin. I see that warning and that's all, it's not possible to use PMA at all.

**Comment by stephen-lin** [comment]
@iamntz What version of Windows are you using?

**Comment by iamntz** [comment]
8.1

**Comment by ericmann** [comment]
Just tested things on an 8.1 x64 box, and it looks like our changes in #167 have corrected the permissions issue.
