### ISSUE TITLE
Allow users to specify their own custom domains

### ISSUE THREAD

**Issue by zamoose** [wpengine/hgv#7]
...in addition to `*.hgv.dev`, of course.

This is going to be a big feature request, I think, so we should be out ahead of it.

**Comment by carmivore** [comment]
+1

**Comment by dbwpe** [comment]
This could help a lot if they end up migrating the site to a web host.  Wouldn't have to change home/siteurl, other database search/replace, etc.

**Comment by markkelnar** [comment]
I believe this primary functionality is provided with https://github.com/wpengine/hgv/pull/154.  

We need to document how to use it.
