### ISSUE TITLE
Suggestion: Move logs to shared folder

### ISSUE THREAD

**Issue by iamntz** [wpengine/hgv#70]
Sometimes is quicker to take a look at logs by just opening from your file browser rather than connecting via ssh and search there, so I guess would be nice to have logs into `hgv_data/logs` or even `hgv_data/sites/SITE_NAME/logs`

**Comment by zamoose** [comment]
@iamntz Have you taken a look at [admin.hgv.dev/logs](http://admin.hgv.dev/logs)? Is there something that we're missing there?

Putting log files on the shared folders is actually going to result in some performance drop-off, so I'd like to avoid it if at all possible.

**Comment by iamntz** [comment]
Oh, obviously enough, I kind of missed that. Thanks!

**Comment by iamntz** [comment]
I think i know why i missed: there is nowhere in the docs! (i'm talking about these docs: http://hgv.dev/#mercury-vagrant-hgv-development-and-debugging-viewing-log-files )

Also, it seems that on a fresh install, doesn't quite work anymore:

![2015-02-12 51_11](https://cloud.githubusercontent.com/assets/132062/6163557/b1cb2fbe-b29c-11e4-8448-63a4a2571726.png)

**Comment by zamoose** [comment]
@iamntz Thanks for pointing this out. I'm working on a solution.

**Comment by zamoose** [comment]
@iamntz #93 addresses this, via the web UI.
