### ISSUE TITLE
Copy dashboard is not idempotent

### ISSUE THREAD

**Issue by markkelnar** [wpengine/hgv#74]
All files for /nas/wp/www/sites/dashboard/ are changed each time.

**Comment by zamoose** [comment]
It does an rsync on the Ansible side of things. Not sure how to get changes
injected shy of making sure they're all updated...

On Mon, Feb 9, 2015 at 1:10 PM, Mark Kelnar <notifications@github.com>
wrote:

> All files for /nas/wp/www/sites/dashboard/ are changed each time.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/issues/74>.
>



-- 
-Doug
