### ISSUE TITLE
MySQL port forwarding not working

### ISSUE THREAD

**Issue by jwhitley** [wpengine/hgv#88]
Per the HGV docs and the Vagrantfile, port forwarding should be enabled so that host-side (OS X 10.10.2 here) MySQL clients can connect to the VM's database via port 23306.  I'm unable to connect to MySQL on this port using `mysql` or MySQL Workbench.  I note that the port is correctly bound on the host:

```
$ lsof -n -i4TCP:23306 | grep LISTEN
VBoxHeadl 91457 whitley   18u  IPv4 0x55db17f086dcb8f9      0t0  TCP *:23306 (LISTEN)
```

What's more, I can connect to the VM's DB if I setup ssh port forwarding.  N.B.: the `vagrant` host below is a [convenience host config](https://gist.github.com/jwhitley/da7f60eb46c1c7e815c3) I setup in `~/.ssh/config` to avoid typing the long ssh incantation that `vagrant ssh` uses.

```
 ssh vagrant -L3333:localhost:3306
```

After running the above port forwarding command, I am then able to connect on the forwarded port (3333 here, not 23306).

It's unclear whether this is an HGV specific bug, e.g. somehow a config problem with Vagrantfile.  Since I found it while using HGV, I'm filing this here as a heads-up and in case it's a known issue.  I'll continue to dig in as work allows and will note any follow-up issues (e.g. against VirtualBox or Vagrant) here.

**Comment by zamoose** [comment]
@jwhitley Thanks! I'll look into this.

**Comment by jwhitley** [comment]
@zamoose FYI, I alluded to a possible Vagrant config problem above.  Vagrant port forwarding working correctly depends to some extent on what kinds of network(s) the VM is configured with.  IIRC, this is mostly a problem when the box has a NAT-only network and nothing else.  I *think* the private network that HGV uses should be OK, and the `lsof` output above would bear that out.  Still, it's an avenue to spelunk down if other stuff fails.

Oh, and I'm on VirtualBox 4.3.20, Vagrant 1.6.5, should that turn out to be relevant.  Hmm, looks like my Vagrant is a touch out of date.  I kinda doubt that's the issue, but I'll update and skim the changelogs for good measure.

**Comment by zamoose** [comment]
@jwhitley This is due to the fact that we're binding to only 127.0.0.1 in the VM. #97 should address this and once it's committed, if you could do a pull and then re-provision, it *should* work.

**Comment by jwhitley** [comment]
@zamoose :+1:  I just gave #97 a spin and it worked great.  Thanks!

**Comment by zamoose** [comment]
Great! Going to close this out then.
