### ISSUE TITLE
Provisioning fails on phpMyAdmin extraction

### ISSUE THREAD

**Issue by clubduece** [wpengine/hgv#90]
TASK: [admin | Download phpMyAdmin] ******************************************* 
ok: [127.0.0.1]
: 
TASK: [admin | Extract phpMyAdmin] ******************************************** 
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: unsupported parameter for module: creates

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/playbook.retry
127.0.0.1                  : ok=102  changed=10   unreachable=0    failed=1

**Comment by zamoose** [comment]
Thanks! I'll take a look. 

--
Doug Stewart

**Comment by zamoose** [comment]
@clubduece:
The `creates` parameter for `unarchive` was added to Ansible in version 1.6. I'm wondering if/why your Ansible didn't get upgraded to the latest. You're probably still back at 1.5.x.

Can you do a `vagrant destroy/up` cycle, by any chance?

**Comment by zamoose** [comment]
@clubduece Actually, this is a regression on HGV's part. Good catch.

We'll either need to revert the `creates` or push #78 into master.

**Comment by markkelnar** [comment]
Should resolved now that #78 has been merged.  Can you confirm?

**Comment by clubduece** [comment]
Sorry for the delay, but yes, the provisioning now works.

**Comment by zamoose** [comment]
Great, thanks @clubduece!

Closing.
