### ISSUE TITLE
Provisioning issues on Windows.

### ISSUE THREAD

**Issue by pbaylies** [wpengine/hgv#96]
I ran into two issues so far on Windows; the first was with the "Fill the varnish GPG Key" task, I sidestepped that by skipping varnish; here's the ugliness:

```
==> hgv: TASK: [varnish | Fill the varnish GPG Key] ************************************
==> hgv: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true, "rc": 2}
==> hgv: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ********************************************************************
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=48   changed=2    unreachable=0    failed=1
```

The second issue was with copying wp-config.php for hhvm - I believe this one is due to an open file system compatibility issue with ansible - https://github.com/ansible/ansible/issues/9526

```
==> hgv: failed: [127.0.0.1] => {"failed": true}
==> hgv: msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1424803253.38-115093539855258/source to /nas/wp/www/sites/hhvm/wp-config.php: [Errno 26] Text file busy
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ********************************************************************
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=58   changed=3    unreachable=0    failed=1
```

**Comment by micfai** [comment]
I am having a similar issue.

```
==> hgv: TASK: [wordpress | Create wp-config for hhvm] *************************
********
==> hgv: failed: [127.0.0.1] => {"failed": true}
==> hgv: msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1425183707.
08-120907877596216/source to /nas/wp/www/sites/hhvm/wp-config.php: [Errno 26] Te
xt file busy
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ************************************************************
********
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=67   changed=57   unreachable=0    failed=1
```

**Comment by zamoose** [comment]
This *appears* to be an issue with Vagrant shared folders on Windows:

https://github.com/ansible/ansible/issues/9526

I will have to see if a solution can be found.

**Comment by iamntz** [comment]
I also have this issue, so i start fiddling around. What i've found? The issue was induced around v1.1 tag 

It's fairly hard to exactly pinpoint, because once the reprovision fails, the box needs to be destroyed and re-init. Right now i'm between a6b2770a50ea802211ac1055a56324500d0ab17b and 95d8899907bb9c69b348b43aa6af4541c533c2c8 (the latter works, the first, which is newer, it doesn't).

I'll post an update when i'll find the bad boy.

**Comment by saada** [comment]
:+1:

**Comment by zamoose** [comment]
@iamntz are you using Git bisect to track this down?

**Comment by iamntz** [comment]
@zamoose no, i never used that. Good ol' `git reset --hard hash`.

**Comment by zamoose** [comment]
@iamntz any further details? Figure out which rev it's occurring at?

**Comment by zamoose** [comment]
Ahh, I see you updated your previous comment.

**Comment by zamoose** [comment]
At least a portion of this issue seems to be related to #108 and the CRLF settings for Windows Git clients.

**Comment by nekojira** [comment]
I also have this error

    ==> test: TASK: [varnish | Fill the varnish GPG Key] ************************************
    ==> test: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true, "rc": 2}
    ==> test: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
    ==> test: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
    ==> test: 
    ==> test: FATAL: all hosts have already failed -- aborting

Vagrant aborts provisioning, the VM can start, hosts are updated and I can still visit http://hgv.dev/ but all the sites will respond with this - wordpress installations are missing

**Comment by nekojira** [comment]
@pbaylies how did you avoid that error by skipping vanish? what do you mean?

**Comment by nekojira** [comment]
ok the first error mentioned by @pbaylies  can be fixed with https://github.com/wpengine/hgv/issues/108#issuecomment-88207928 -

still looking for a solution to the second error

**Comment by iamntz** [comment]
I'm not sure if this is really fixed. I cloned the repo, fired up an admin console, `vagrant up`, entered my windows user/password and...

```
==> hgv-test: TASK: [wp-cli | Create install location for WP-CLI] ***************************
==> hgv-test: changed: [127.0.0.1]
==> hgv-test:
==> hgv-test: TASK: [wp-cli | Install WP-CLI] ***********************************************
==> hgv-test: changed: [127.0.0.1]
==> hgv-test:
==> hgv-test: TASK: [wp-cli | Set execute bits on WP-CLI] ***********************************
==> hgv-test: changed: [127.0.0.1]
==> hgv-test:
==> hgv-test: TASK: [wp-cli | Symlink WP-CLI] ***********************************************
==> hgv-test: changed: [127.0.0.1]
==> hgv-test:
==> hgv-test: TASK: [varnish | Fill the varnish GPG Key] ************************************
==> hgv-test: failed: [127.0.0.1] => {"cmd": "apt-key add -", "failed": true, "rc": 2}
==> hgv-test: stderr: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv-test:
==> hgv-test: msg: gpg: invalid armor header: mQINBEyHLzoBEACwWIEvQ1PysbHP1zxMaRzcKC1+ZzIOB7yt59obMxgr+leU/wxq\n
==> hgv-test:
==> hgv-test: FATAL: all hosts have already failed -- aborting
==> hgv-test:
==> hgv-test: PLAY RECAP ********************************************************************
==> hgv-test:            to retry, use: --limit @/root/playbook.retry
==> hgv-test: 127.0.0.1                  : ok=59   changed=51   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

C:\work\hgv-test>
```

**Comment by ericmann** [comment]
@iamntz The issue you're facing is related, but a bit separate to the one we fixed. This ticket documented _two_ issues:

- VirtualBox shares failing to properly set file permissions on Windows
- Windows checkouts changing line endings from LF to CRLF

The first issue (VirtualBox shares) was corrected by #167.
The second issue was corrected in #108.

_However_ the fix in #108 will only automatically fix new clones of Hgv, not existing ones. In a nutshell, our code forces Git to respect Unix-style line endings upon checkout regardless of your system settings (which, in this case, appear to be set to CRLF).

If you don't want to start with a clean install, you'll need to [get Hgv set back to the correct line ending format](108#issuecomment-88207928).  You can do that by:

- `vagrant ssh`
- `sudo apt-get install dos2unix`
- `sudo dos2unix /vagrant/provisioning/roles/varnish/files/varnish-cache.gpg.key`
- Try `vagrant provision` again.

This will install and use the `dos2unix` utility to reset the line endings of the corrupt file before you re-provision.

**Comment by iamntz** [comment]
Thanks for reply @ericmann 

As I stated above: 

> I cloned the repo

As in i cloned just before i ran `vagrant up`.

I tried to clone from a regular user prompt and from an admin prompt, and... didn't worked. 

I'm running right now `vagrant up` and I'll try your workaround. I'll let you know. Thanks!

**Comment by iamntz** [comment]
Just a heads up, I successfully make it work by doing this way:

1. Cloning the repo
- open bash shell (git bash will do)
- run `cd hgv/provisioning && find . -type f -exec dos2unix {} \;`
- open Admin cmd & `vagrant up`

Yay!

This is the only error i found:

```
==> hgv:
==> hgv: TASK: [wordpress | Check whether the WP install has been run previously] ******
==> hgv: failed: [127.0.0.1] => {"changed": true, "cmd": ["/usr/local/bin/wp", "core", "is-installed", "--path=/nas/wp/www/sites/hhvm"], "de
lta": "0:00:00.552781", "end": "2015-06-21 08:55:06.386602", "rc": 1, "start": "2015-06-21 08:55:05.833821", "warnings": []}
==> hgv: ...ignoring
```
