### ISSUE TITLE
Styling issues on wide screens

### ISSUE THREAD

**Issue by JPry** [wpengine/hgv#99]
Some elements of the main hgv.dev page are pushed out to the right on wider screens. Most notable are `<blockquote>`, `<code>` and `<pre>` elements. Here's a screenshot from Safari:

![](https://photos-5.dropbox.com/t/2/AAAgP9sqKzgd6DmqOaykB0Nba7xM8u7To1GaWWgztUqdeg/12/5658580/png/1024x768/3/1425870000/0/2/Screenshot%202015-03-08%2021.57.42.png/CNSv2QIgASACIAMoASgCKAM/UbW2PdqC_NEgy2JMEbaQjQxMLGCgoCv95uGaB1jDokM)

These issues do not show up once the screen width shrinks to 1180 pixels or less.

**Comment by zamoose** [comment]
#47 a possible (overkill) solution.

**Comment by zamoose** [comment]
Ahh, missed the screenshot the first time @JPry. That's the way Flatdoc does blockquotes and code snippets by default. 

We can disable this behavior by default [if we want to](http://ricostacruz.com/flatdoc/#customizing-basic-theme-options).
